
import { Building, Role } from '../types';

export const ALL_BUILDINGS: Building[] = [
  // ACUARTELAMIENTO “ALFÉREZ ROJAS NAVARRETE
  { id: 'E0001', name: 'CÁMARA SIM', code: 'E0001', unit: 'USAC', hasBoiler: false },
  { id: 'E0002', name: 'GRUPO CUARTEL GENERAL DEL MOE', code: 'E0002', unit: 'GCG', hasBoiler: false },
  { id: 'E0003', name: 'GOE III', code: 'E0003', unit: 'GOE3', hasBoiler: false },
  { id: 'E0004', name: 'BOEL XIX', code: 'E0004', unit: 'BOEL', hasBoiler: false },
  { id: 'E0005', name: 'GOE IV', code: 'E0005', unit: 'GOE4', hasBoiler: false },
  { id: 'E0006', name: 'ALOJAMIENTO TROPA B', code: 'E0006', unit: 'USAC', hasBoiler: false },
  { id: 'E0007', name: 'VESTUARIO DE MANDOS', code: 'E0007', unit: 'USAC', hasBoiler: true },
  { id: 'E0008', name: 'CUERPO DE GUARDIA', code: 'E0008', unit: 'USAC', hasBoiler: false },
  { id: 'E0009', name: 'USAC', code: 'E0009', unit: 'USAC', hasBoiler: false },
  { id: 'E0010', name: 'VESTUARIO CGC y GOE III', code: 'E0010', unit: 'GCG', hasBoiler: true },
  { id: 'E0011', name: 'TRANSEÚNTES 1 Y 2', code: 'E0011', unit: 'USAC', hasBoiler: false },
  { id: 'E0012', name: 'CECOM', code: 'E0012', unit: 'CECOM', hasBoiler: false },
  { id: 'E0013', name: 'SAE MOE', code: 'E0013', unit: 'UMOE', hasBoiler: false },
  { id: 'E0014', name: 'SALÓN DE ACTOS / GIMNASIO', code: 'E0014', unit: 'USAC', hasBoiler: false },
  { id: 'E0015', name: 'ALMACENES IMPEDIMENTA VEHÍCULOS MOE', code: 'E0015', unit: 'UMOE', hasBoiler: false },
  { id: 'E0016', name: 'OFICINA TRANSPORTES ULOG MOE', code: 'E0016', unit: 'UMOE', hasBoiler: false },
  { id: 'E0017', name: 'JOC (Joint Operation Center)', code: 'E0017', unit: 'GCG', hasBoiler: false },
  { id: 'E0018', name: 'ULOG MOE', code: 'E0018', unit: 'UMOE', hasBoiler: false },
  { id: 'E0019', name: 'DEPOSITO DE MUNICIÓN A', code: 'E0019', unit: 'USAC', hasBoiler: false },
  { id: 'E0020', name: 'DEPOSITO DE MUNICIÓN B', code: 'E0020', unit: 'USAC', hasBoiler: false },
  { id: 'E0021', name: 'ALOJAMIENTO LOGÍSTICO TROPA E1- E2', code: 'E0021', unit: 'USAC', hasBoiler: false },
  { id: 'E0022', name: 'BOTIQUÍN', code: 'E0022', unit: 'USAC', hasBoiler: false },
  { id: 'E0023', name: 'COMEDOR', code: 'E0023', unit: 'USAC', hasBoiler: false },
  { id: 'E0024', name: 'ALOJAMIENTO LOGÍSTICO TROPA C', code: 'E0024', unit: 'USAC', hasBoiler: false },
  { id: 'E0025', name: 'ALOJAMIENTO LOGÍSTICO TROPA D-1-2-3', code: 'E0025', unit: 'USAC', hasBoiler: false },
  { id: 'E0026', name: 'ALOJAMIENTO LOGÍSTICO TROPA E3-E4', code: 'E0026', unit: 'USAC', hasBoiler: false },
  { id: 'E0027', name: 'ALMACEN LAVANDERÍA', code: 'E0027', unit: 'USAC', hasBoiler: false },
  { id: 'E0028', name: 'ABE/SETRE', code: 'E0028', unit: 'USAC', hasBoiler: false },
  { id: 'E0029', name: 'CATOE', code: 'E0029', unit: 'USAC', hasBoiler: false },
  { id: 'E0030', name: 'CASOE', code: 'E0030', unit: 'USAC', hasBoiler: false },
  { id: 'E0031', name: 'DESPACHO DEL PATER', code: 'E0031', unit: 'USAC', hasBoiler: false },
  { id: 'E0032', name: 'MANTENIMIENTO USAC', code: 'E0032', unit: 'USAC', hasBoiler: false },
  { id: 'E0033', name: 'ALMACEN USAC', code: 'E0033', unit: 'USAC', hasBoiler: false },
  { id: 'E0034', name: 'ALMACÉN JARDINERÍA', code: 'E0034', unit: 'USAC', hasBoiler: false },
  { id: 'E0035', name: 'CAPILLA', code: 'E0035', unit: 'USAC', hasBoiler: false },
  { id: 'E0036', name: 'CASETA', code: 'E0036', unit: 'USAC', hasBoiler: false },
  { id: 'E0037', name: 'CASETA ALMACÉN SAE', code: 'E0037', unit: 'UMOE', hasBoiler: false },
  { id: 'E0038', name: 'CABINA DE PINTURA', code: 'E0038', unit: 'USAC', hasBoiler: false },
  { id: 'E0039', name: 'REWE 32', code: 'E0039', unit: 'USAC', hasBoiler: false },
  { id: 'E0040', name: 'ALMACEN GCG', code: 'E0040', unit: 'GCG', hasBoiler: false },
  { id: 'E0042', name: 'LAVANDERÍA', code: 'E0042', unit: 'USAC', hasBoiler: false },
  { id: 'E0043', name: 'ALMACÉN GOE', code: 'E0043', unit: 'GOE3', hasBoiler: false },
  { id: 'E0044', name: 'ALMACÉN GENERAL MOE', code: 'E0044', unit: 'UMOE', hasBoiler: false },
  { id: 'E0045', name: '2º ESCALÓN DE MANTENIMIENTO MOE', code: 'E0045', unit: 'UMOE', hasBoiler: false },
  { id: 'E0046', name: 'ALMACÉN USAC', code: 'E0046', unit: 'USAC', hasBoiler: false },
  { id: 'E0047', name: 'EDIFICIO EN RUINA', code: 'E0047', unit: 'USAC', hasBoiler: false },
  { id: 'E0048', name: 'VESTUARIO BOEL XIX', code: 'E0048', unit: 'BOEL', hasBoiler: true },
  { id: 'E0049', name: 'VESTUARIO PISCINA SOCIAL', code: 'E0049', unit: 'USAC', hasBoiler: false },
  { id: 'E0050', name: 'UNIDAD DE INSTRUCCIÓN DE OPERACIONES ESPECIALES', code: 'E0050', unit: 'USAC', hasBoiler: false },
  { id: 'E0051', name: 'ALMACEN', code: 'E0051', unit: 'USAC', hasBoiler: false },
  { id: 'E0052', name: 'ALMACEN', code: 'E0052', unit: 'USAC', hasBoiler: false },
  { id: 'E0053', name: 'SID', code: 'E0053', unit: 'USAC', hasBoiler: false },
  { id: 'E0054', name: 'ALMACEN DE MANTENIMIENTO USAC', code: 'E0054', unit: 'USAC', hasBoiler: false },
  { id: 'E0055', name: 'CASETA VESTUARIO', code: 'E0055', unit: 'USAC', hasBoiler: false },
  { id: 'E0056', name: 'VESTUARIO DE TROPA FEMENINO', code: 'E0056', unit: 'USAC', hasBoiler: true },
  { id: 'E0057', name: 'GARITA CONTROL DE ACCESOS', code: 'E0057', unit: 'USAC', hasBoiler: false },
  { id: 'E0058', name: 'ALMACÉN CECOM/GOE IV', code: 'E0058', unit: 'CECOM', hasBoiler: false },
  { id: 'E0059', name: 'VESTUARIO GOE IV', code: 'E0059', unit: 'GOE4', hasBoiler: true },
  { id: 'E0060', name: 'ALMACENES GOE', code: 'E0060', unit: 'GOE3', hasBoiler: false },
  { id: 'E0061', name: 'ALMACÉN MATERIAL DE AGUA MOE', code: 'E0061', unit: 'UMOE', hasBoiler: false },
  { id: 'E0062', name: 'PERRERAS 1', code: 'E0062', unit: 'USAC', hasBoiler: false },
  { id: 'E0063', name: 'PERRERAS 2', code: 'E0063', unit: 'USAC', hasBoiler: false },
  { id: 'E0064', name: 'ALOJAMIENTO LOGÍSTICO DE MANDOS 3', code: 'E0064', unit: 'USAC', hasBoiler: true },
  { id: 'E0065', name: 'ESTADO MAYOR DEL MOE', code: 'E0065', unit: 'USAC', hasBoiler: true },
  { id: 'E0066', name: 'EDIFICIO MANDO MOE', code: 'E0066', unit: 'USAC', hasBoiler: false },
  { id: 'E0067', name: 'CAFETERÍAS', code: 'E0067', unit: 'USAC', hasBoiler: false },
  { id: 'E0068', name: 'ALOJAMIENTO LOGÍSTICO DE TROPA A', code: 'E0068', unit: 'USAC', hasBoiler: true },
  { id: 'E0069', name: 'ANTIGUOS TALLERES USAC', code: 'E0069', unit: 'USAC', hasBoiler: false },
  { id: 'E0070', name: 'REFUGIO 1', code: 'E0070', unit: 'USAC', hasBoiler: false },
  { id: 'E0071', name: 'AULAS', code: 'E0071', unit: 'USAC', hasBoiler: false },
  { id: 'E0072', name: 'ALOJAMIENTO LOGÍSTICO TROPA D-4', code: 'E0072', unit: 'USAC', hasBoiler: false },
  { id: 'E0073', name: '2º ESCALÓN MANTENIMIENTO RUEDAS MOE', code: 'E0073', unit: 'UMOE', hasBoiler: false },
  { id: 'E0074', name: 'REFUGIO 2', code: 'E0074', unit: 'USAC', hasBoiler: false },
  { id: 'E0075', name: 'REFUGIO 3', code: 'E0075', unit: 'USAC', hasBoiler: false },
  { id: 'E0076', name: 'REFUGIO 4', code: 'E0076', unit: 'USAC', hasBoiler: false },
  { id: 'E0077', name: 'GABINETE AUDIOVISUAL MOE', code: 'E0077', unit: 'USAC', hasBoiler: false },
  { id: 'E0078', name: 'ANTIGUOS ASEOS', code: 'E0078', unit: 'USAC', hasBoiler: false },

  // INSTALACIONES
  { id: 'CT_1_2', name: 'TRANSFORMADOR ELÉCTRICO 1 y 2', code: 'I0001', unit: 'USAC', hasBoiler: false },
  { id: 'CT_3', name: 'TRANSFORMADOR ELÉCTRICO 3', code: 'I0002', unit: 'USAC', hasBoiler: false },
  { id: 'BASE_ALICANTE', name: 'Base Alicante (Contador General)', code: 'ALC-GEN', unit: 'USAC', hasBoiler: false },
  { id: 'I0003', name: 'ECOPARQUE', code: 'I0003', unit: 'USAC', hasBoiler: false },
  { id: 'I0004', name: 'PUNTO LIMPIO RESIDUOS PELIGROSOS', code: 'I0004', unit: 'USAC', hasBoiler: false },
  { id: 'I0005', name: 'PISCINA SOCIAL', code: 'I0005', unit: 'USAC', hasBoiler: false },
  { id: 'I0006', name: 'PISCINA DE INSTRUCCIÓN', code: 'I0006', unit: 'USAC', hasBoiler: false },
  { id: 'I0007', name: 'DEPURADORA PISCINA SOCIAL', code: 'I0007', unit: 'USAC', hasBoiler: false },
  { id: 'I0008', name: 'DEPURADORA PISCINA I/A/E', code: 'I0008', unit: 'USAC', hasBoiler: false },
  { id: 'I0009', name: 'DEPÓSITO GLP COCINA', code: 'I0009', unit: 'USAC', hasBoiler: false },
  { id: 'I0010', name: 'ANTIGUO DEPÓSITO AÉREO DE AGUA', code: 'I0010', unit: 'USAC', hasBoiler: false },
  { id: 'I0011', name: 'BOX CROSSFIT 1', code: 'I0011', unit: 'USAC', hasBoiler: false },
  { id: 'I0012', name: 'CAMPO DE ANTENAS REWE 32', code: 'I0012', unit: 'USAC', hasBoiler: false },
  { id: 'I0013', name: 'PISTAS DEPORTIVAS NORTE', code: 'I0013', unit: 'USAC', hasBoiler: false },
  { id: 'I0014', name: 'PISTAS DEPORTIVAS SUR', code: 'I0014', unit: 'USAC', hasBoiler: false },
  { id: 'I0015', name: 'PISTA DE APLICACIÓN', code: 'I0015', unit: 'USAC', hasBoiler: false },
  { id: 'I0016', name: 'PISTA DE INSTRUCCIÓN', code: 'I0016', unit: 'USAC', hasBoiler: false },
  { id: 'I0017', name: 'POLÍGONO DE COMBATE URBANO', code: 'I0017', unit: 'USAC', hasBoiler: false },
  { id: 'I0018', name: 'HELIPUERTO', code: 'I0018', unit: 'USAC', hasBoiler: false },
  { id: 'I0019', name: 'GALERIA DE TIRO', code: 'I0019', unit: 'USAC', hasBoiler: false },
  { id: 'I0020', name: 'ANTIGUO DEPOSITO DE AGUA E', code: 'I0020', unit: 'USAC', hasBoiler: false },
  { id: 'I0021', name: 'GASOLINERA MOE', code: 'I0021', unit: 'USAC', hasBoiler: false },
  { id: 'I0022', name: 'LAVADERO ACTO', code: 'I0022', unit: 'USAC', hasBoiler: false },
  { id: 'I0023', name: 'APARCAMIENTO VEHÍCULOS USAC', code: 'I0023', unit: 'USAC', hasBoiler: false },
  { id: 'I0024', name: 'APARCAMIENTO VEHÍCULOS MOE', code: 'I0024', unit: 'USAC', hasBoiler: false },
  { id: 'I0025', name: 'APARCAMIENTO VEHÍCULOS VEMPAR 1', code: 'I0025', unit: 'USAC', hasBoiler: false },
  { id: 'I0026', name: 'APARCAMIENTO VEHÍCULOS VEMPAR 2', code: 'I0026', unit: 'USAC', hasBoiler: false },
  { id: 'I0027', name: 'APARCAMIENTO A', code: 'I0027', unit: 'USAC', hasBoiler: false },
  { id: 'I0028', name: 'APARCAMIENTO C', code: 'I0028', unit: 'USAC', hasBoiler: false },
  { id: 'I0029', name: 'APARCAMIENTO D', code: 'I0029', unit: 'USAC', hasBoiler: false },
  { id: 'I0030', name: 'APARCAMIENTO E', code: 'I0030', unit: 'USAC', hasBoiler: false },
  { id: 'I0031', name: 'APARCAMIENTO F', code: 'I0031', unit: 'USAC', hasBoiler: false },
  { id: 'I0032', name: 'APARCAMIENTO H', code: 'I0032', unit: 'USAC', hasBoiler: false },
  { id: 'I0033', name: 'DEPOSITO CALDERA C007-1', code: 'I0033', unit: 'USAC', hasBoiler: false },
  { id: 'I0034', name: 'TRIBUNA EXPLANADA DE ARMAS', code: 'I0034', unit: 'USAC', hasBoiler: false },
  { id: 'I0035', name: 'DEPÓSITO CALDERA 007-2', code: 'I0035', unit: 'USAC', hasBoiler: false },
  { id: 'I0036', name: 'DEPÓSITO CALDERA C-010', code: 'I0036', unit: 'USAC', hasBoiler: false },
  { id: 'I0037', name: 'DEPÓSITO CALDERA C-042', code: 'I0037', unit: 'USAC', hasBoiler: false },
  { id: 'I0038', name: 'DEPÓSITO CALDERA C-056', code: 'I0038', unit: 'USAC', hasBoiler: false },
  { id: 'I0039', name: 'DEPÓSITO CALDERA C-059', code: 'I0039', unit: 'USAC', hasBoiler: false },
  { id: 'I0040', name: 'ANTENA DE COMUNICACIONES SCTM', code: 'I0040', unit: 'USAC', hasBoiler: false },
  { id: 'I0041', name: 'APARCAMIENTO VEHÍCULOS GENERAL JEFE MOE', code: 'I0041', unit: 'USAC', hasBoiler: false },
  { id: 'I0042', name: 'ANTIGUAS PERRERAS', code: 'I0042', unit: 'USAC', hasBoiler: false },
  { id: 'I0043', name: 'DEPÓSITO CALDERA C-064', code: 'I0043', unit: 'USAC', hasBoiler: false },
  { id: 'I0044', name: 'DEPÓSITO CALDERA C-065', code: 'I0044', unit: 'USAC', hasBoiler: false },
  { id: 'I0045', name: 'DEPÓSITO CALDERA C-068', code: 'I0045', unit: 'USAC', hasBoiler: false },
  { id: 'I0046', name: 'DEPÓSITO GASÓLEO GASOLINERA', code: 'I0046', unit: 'USAC', hasBoiler: false },
  { id: 'I0047', name: 'DEPÓSITO CALDERA C-048', code: 'I0047', unit: 'USAC', hasBoiler: false },
  { id: 'I0048', name: 'CASA DE TRES ALTURAS I/A', code: 'I0048', unit: 'USAC', hasBoiler: false },
  { id: 'I0049', name: 'TORRE MULTIUSOS', code: 'I0049', unit: 'USAC', hasBoiler: false },
  { id: 'I0050', name: 'POLÍGONO DE COMBATE URBANO', code: 'I0050', unit: 'USAC', hasBoiler: false },
  { id: 'I0051', name: 'PARQUE DE CALISTENIA', code: 'I0051', unit: 'USAC', hasBoiler: false },
  { id: 'I0052', name: 'BOX CROSSFIT 2', code: 'I0052', unit: 'USAC', hasBoiler: false },
  { id: 'I0053', name: 'TINGLADOS ALMACENES', code: 'I0053', unit: 'USAC', hasBoiler: false },

  // URBANIZACIÓN
  { id: 'U0001', name: 'EXPLANADA DE ESTACIONAMIENTO B', code: 'U0001', unit: 'USAC', hasBoiler: false },
  { id: 'U0002', name: 'EXPLANADA DE ESTACIONAMIENTO G', code: 'U0002', unit: 'USAC', hasBoiler: false },
  { id: 'U0003', name: 'TENDEDERO DE SÁBANAS', code: 'U0003', unit: 'USAC', hasBoiler: false },
  { id: 'U0004', name: 'JARDÍN DETRÁS MONUMENTO CIR 8', code: 'U0004', unit: 'USAC', hasBoiler: false },
  { id: 'U0005', name: 'VALLADOS', code: 'U0005', unit: 'USAC', hasBoiler: false },
  { id: 'U0006', name: 'JARDÍN PLAZA SAN FERNANDO', code: 'U0006', unit: 'USAC', hasBoiler: false },
  { id: 'U0007', name: 'JARDÍN ALOJAMIENTO TROPA A', code: 'U0007', unit: 'USAC', hasBoiler: false },
  { id: 'U0008', name: 'JARDÍN ZONA DE MANDO', code: 'U0008', unit: 'USAC', hasBoiler: false },
  { id: 'U0009', name: 'EXPLANADA DE ACTOS', code: 'U0009', unit: 'USAC', hasBoiler: false },
  { id: 'U0010', name: 'ACERAS', code: 'U0010', unit: 'USAC', hasBoiler: false },
  { id: 'U0011', name: 'VIALES', code: 'U0011', unit: 'USAC', hasBoiler: false },
  { id: 'U0012', name: 'CAMINOS', code: 'U0012', unit: 'USAC', hasBoiler: false },
  { id: 'U0013', name: 'VALLADO DEPÓSITO EXTERIOR GAS COCINA', code: 'U0013', unit: 'USAC', hasBoiler: false },
  { id: 'U0014', name: 'VALLADO DEPÓSITO EXTERIOR CALDERA LAVANDERÍA', code: 'U0014', unit: 'USAC', hasBoiler: false },
  { id: 'U0015', name: 'DEPÓSITO EXTERIOR CALDERA 007-2', code: 'U0015', unit: 'USAC', hasBoiler: false },
  { id: 'U0016', name: 'CANALIZACIÓN AGUA POTABLE', code: 'U0016', unit: 'USAC', hasBoiler: false },
  { id: 'U0017', name: 'CANALIZACIÓN DE DESAGÜE', code: 'U0017', unit: 'USAC', hasBoiler: false },
  { id: 'U0018', name: 'CANALIZACIÓN MEDIA TENSIÓN', code: 'U0018', unit: 'USAC', hasBoiler: false },
  { id: 'U0019', name: 'ACOMETIDA ELÉCTRICA ENTRADA A EDIFICIOS', code: 'U0019', unit: 'USAC', hasBoiler: false },
  { id: 'U0020', name: 'CANALIZACIÓN ILUMINACIÓN EXTERIOR', code: 'U0020', unit: 'USAC', hasBoiler: false },
  { id: 'U0021', name: 'CANALIZACIÓN TELECOMUNICACIONES', code: 'U0021', unit: 'USAC', hasBoiler: false },
  { id: 'U0022', name: 'PUERTA ACCESO PRINCIPAL', code: 'U0022', unit: 'USAC', hasBoiler: false },
  { id: 'U0023', name: 'PUERTA ACCESO NORTE', code: 'U0023', unit: 'USAC', hasBoiler: false },
  { id: 'U0024', name: 'PUERTA ACCESO ESTE', code: 'U0024', unit: 'USAC', hasBoiler: false },
  { id: 'U0025', name: 'PUERTA ACCESO OESTE', code: 'U0025', unit: 'USAC', hasBoiler: false },
  { id: 'U0026', name: 'MURO PERIMETRAL', code: 'U0026', unit: 'USAC', hasBoiler: false },
  { id: 'U0027', name: 'TERRENO SIN URBANIZAR', code: 'U0027', unit: 'USAC', hasBoiler: false },
  { id: 'U0028', name: 'MONUMENTO A LOS CAIDOS', code: 'U0028', unit: 'USAC', hasBoiler: false },
  { id: 'U0029', name: 'MONUMENTO MOE PATIO DE ARMAS', code: 'U0029', unit: 'USAC', hasBoiler: false },
  { id: 'U0030', name: 'MONUMENTO ANTIGUO ALTAR PATIO DE ARMAS', code: 'U0030', unit: 'USAC', hasBoiler: false },
  { id: 'U0031', name: 'MONUMENTO AL GRANADERO', code: 'U0031', unit: 'USAC', hasBoiler: false },
  { id: 'U0032', name: 'MONUMENTO COE 71', code: 'U0032', unit: 'USAC', hasBoiler: false },
  { id: 'U0033', name: 'MONUMENTO AL CIR 8', code: 'U0033', unit: 'USAC', hasBoiler: false },
  { id: 'U0034', name: 'MONUMENTO DE PIEDRA PLAZA SAN FERNANDO', code: 'U0034', unit: 'USAC', hasBoiler: false },
  { id: 'U0035', name: 'MONUMENTO A LA FAMILIA', code: 'U0035', unit: 'USAC', hasBoiler: false },
  { id: 'U0036', name: 'JARDÍN ZONA CAFETERÍAS', code: 'U0036', unit: 'USAC', hasBoiler: false },
  { id: 'U0037', name: 'JARDÍN EDIFICIO USAC', code: 'U0037', unit: 'USAC', hasBoiler: false },
  { id: 'U0038', name: 'JARDÍN EDIFICIO TRANSEÚNTES', code: 'U0038', unit: 'USAC', hasBoiler: false },
  { id: 'U0039', name: 'JARDÍN EDIFICIO BOTIQUÍN/ALOJAMIENTO C', code: 'U0039', unit: 'USAC', hasBoiler: false },
  { id: 'U0040', name: 'JARDÍN EDIFICIO VESTUARIO GCG/GOE III', code: 'U0040', unit: 'GCG', hasBoiler: false },
  { id: 'U0041', name: 'MONUMENTO AL GUERRILLERO', code: 'U0041', unit: 'USAC', hasBoiler: false },
  { id: 'U0042', name: 'JARDÍN PATIO DE ARMAS', code: 'U0042', unit: 'USAC', hasBoiler: false },
  { id: 'U0043', name: 'JARDÍN APARCAMIENTO C', code: 'U0043', unit: 'USAC', hasBoiler: false },
  { id: 'U0044', name: 'JARDÍN EDIFICIO DE AULAS', code: 'U0044', unit: 'USAC', hasBoiler: false },
  { id: 'U0045', name: 'JARDÍN EDIFICIO MANTENIMIENTO', code: 'U0045', unit: 'USAC', hasBoiler: false },
  { id: 'U0046', name: 'JARDÍN CAPILLA', code: 'U0046', unit: 'USAC', hasBoiler: false },
  { id: 'U0047', name: 'JARDÍN EDIFICIO SALA OSCURA', code: 'U0047', unit: 'USAC', hasBoiler: false },
  { id: 'U0048', name: 'JARDÍN EDIFICIO ALOJAMIENTO D', code: 'U0048', unit: 'USAC', hasBoiler: false },
  { id: 'U0049', name: 'JARDÍN EDIFICIO ALOJAMIENTO E', code: 'U0049', unit: 'USAC', hasBoiler: false },
  { id: 'U0050', name: 'JARDÍN APARCAMIENTO B', code: 'U0050', unit: 'USAC', hasBoiler: false },
  { id: 'U0051', name: 'JARDÍN CALLE EDIFICIO MANDO/EM/VESTUARIO MANDOS', code: 'U0051', unit: 'USAC', hasBoiler: false },

  // CMT AGOST
  { id: 'AGOST_I0001', name: 'PCZURB (AGOST)', code: 'I0001', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0002', name: 'POLÍGONO C-IED (AGOST)', code: 'I0002', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0003', name: 'EDIFICIO DE TIRADORES DE PRECISIÓN (AGOST)', code: 'I0003', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0004', name: 'ASENTAMIENTO DE TIRADORES DE PRECISIÓN (AGOST)', code: 'I0004', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0005', name: 'FACHADA DE OBJETIVOS (AGOST)', code: 'I0005', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0006', name: 'ESTRUCTURA HORMIGÓN PARA BLANCOS MÓVILES (AGOST)', code: 'I0006', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0007', name: 'BLANCOS CON PARAPETO DE HORMIGÓN (AGOST)', code: 'I0007', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0008', name: 'CASETA MATERIAL TIRADORES (AGOST)', code: 'I0008', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0009', name: 'HELIPUERTO (AGOST)', code: 'I0009', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0010', name: 'CAMPO DE TIRO (AGOST)', code: 'I0010', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0011', name: 'CONTENEDOR MATERIAL CONTRAINCENDIOS (AGOST)', code: 'I0011', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0012', name: 'CAMPO DE EXPLOSIVOS (AGOST)', code: 'I0012', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0013', name: 'CAMPO DE GRANADAS DE MANO (AGOST)', code: 'I0013', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0014', name: 'PASILLO DE FUEGO (AGOST)', code: 'I0014', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_I0015', name: 'PISTA CONDUCCIÓN TT (AGOST)', code: 'I0015', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_U0001', name: 'VALLADO PERIMETRAL CMT (AGOST)', code: 'U0001', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_U0002', name: 'VALLADO INTERIOR (AGOST)', code: 'U0002', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_U0003', name: 'CAMINOS (AGOST)', code: 'U0003', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_U0004', name: 'CANALIZACIÓN DE AGUA POTABLE (AGOST)', code: 'U0004', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_U0005', name: 'ZONA VIVAC (AGOST)', code: 'U0005', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_U0006', name: 'ZONA DE CAÍDA DE PROYECTILES (AGOST)', code: 'U0006', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_U0007', name: 'PUERTA DE ACCESO PRINCIPAL (AGOST)', code: 'U0007', unit: 'USAC', hasBoiler: false },
  { id: 'AGOST_U0008', name: 'PUERTA DE ACCESO SECUNDARIO (AGOST)', code: 'U0008', unit: 'USAC', hasBoiler: false },

  // CMT FONTCALENT
  { id: 'FONT_I0001', name: 'TECHADO DE TIRADORES (FONTCALENT)', code: 'I0001', unit: 'USAC', hasBoiler: false },
  { id: 'FONT_U0001', name: 'CANCHA DE TIRO 1 (FONTCALENT)', code: 'U0001', unit: 'USAC', hasBoiler: false },
  { id: 'FONT_U0002', name: 'CANCHA DE TIRO 2 (FONTCALENT)', code: 'U0002', unit: 'USAC', hasBoiler: false },
  { id: 'FONT_U0003', name: 'CANCHA DE TIRO 3 (FONTCALENT)', code: 'U0003', unit: 'USAC', hasBoiler: false },
  { id: 'FONT_U0004', name: 'MERLÓN 1 (FONTCALENT)', code: 'U0004', unit: 'USAC', hasBoiler: false },
  { id: 'FONT_U0005', name: 'MERLÓN 2 (FONTCALENT)', code: 'U0005', unit: 'USAC', hasBoiler: false },
  { id: 'FONT_U0006', name: 'MURO PERIMETRAL (FONTCALENT)', code: 'U0006', unit: 'USAC', hasBoiler: false },
  { id: 'FONT_U0007', name: 'VALLADO PERIMETRAL (FONTCALENT)', code: 'U0007', unit: 'USAC', hasBoiler: false },
  { id: 'FONT_U0008', name: 'CAMINOS (FONTCALENT)', code: 'U0008', unit: 'USAC', hasBoiler: false },
  { id: 'FONT_U0009', name: 'TERRENO SIN URBANIZAR (FONTCALENT)', code: 'U0009', unit: 'USAC', hasBoiler: false },
  { id: 'FONT_U0010', name: 'PUERTA DE ACCESO PRINCIPAL (FONTCALENT)', code: 'U0010', unit: 'USAC', hasBoiler: false },
  { id: 'FONT_U0011', name: 'PUERTA DE ACCESO SECUNDARIO (FONTCALENT)', code: 'U0011', unit: 'USAC', hasBoiler: false },

  // CABO ROIG
  { id: 'CABO_E0001', name: 'ALOJAMIENTO DEL PERSONAL (CABO ROIG)', code: 'E0001', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_E0002', name: 'ALOJAMIENTO DEL PERSONAL (CABO ROIG)', code: 'E0002', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_E0003', name: 'ALOJAMIENTO DEL PERSONAL (CABO ROIG)', code: 'E0003', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_E0004', name: 'ZONA DE VIDA (CABO ROIG)', code: 'E0004', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_E0005', name: 'ALMACÉN MATERIAL DE AGUA (CABO ROIG)', code: 'E0005', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_E0006', name: 'OFICINA DESTACAMENTO/DORMITORIO (CABO ROIG)', code: 'E0006', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_E0007', name: 'ANEXO EDIFICIO 3 (ASEOS GENERALES) (CABO ROIG)', code: 'E0007', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_E0008', name: 'BOTIQUÍN (CABO ROIG)', code: 'E0008', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_E0009', name: 'ANEXO EDIFICIO 4 (COCINA) (CABO ROIG)', code: 'E0009', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_E0010', name: 'ANEXO EDIFICIO 4 (DORMITORIO) (CABO ROIG)', code: 'E0010', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_E0011', name: 'ANEXO EDIFICIO 2 (ASEO) (CABO ROIG)', code: 'E0011', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_E0012', name: 'ANEXO EDIFICIO 2 (CAFETERÍA) (CABO ROIG)', code: 'E0012', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_E0013', name: 'CUARTO DE TERMOS (CABO ROIG)', code: 'E0013', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_I0001', name: 'TECHADO NORTE (CABO ROIG)', code: 'I0001', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_I0002', name: 'TECHADO PATIO INTERIOR (CABO ROIG)', code: 'I0002', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_I0003', name: 'TORRE VIGILANCIA MARÍTIMA (CABO ROIG)', code: 'I0003', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_I0004', name: 'TECHADO BARBACOA (CABO ROIG)', code: 'I0004', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_I0005', name: 'TECHADO EMBARCACIONES (CABO ROIG)', code: 'I0005', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0001', name: 'PATIO INTERIOR (CABO ROIG)', code: 'U0001', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0002', name: 'ZONA ENDULZADO (CABO ROIG)', code: 'U0002', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0003', name: 'VALLADO PERIMETRAL (CABO ROIG)', code: 'U0003', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0004', name: 'MURO PERIMETRAL (CABO ROIG)', code: 'U0004', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0005', name: 'PUERTA DE ACCESO PRINCIPAL (CABO ROIG)', code: 'U0005', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0006', name: 'PUERTA DE ACCESO SECUNDARIO (CABO ROIG)', code: 'U0006', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0007', name: 'PUERTA DE ACCESO LATERAL (CABO ROIG)', code: 'U0007', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0008', name: 'ZONAS AJARDINADAS (CABO ROIG)', code: 'U0008', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0009', name: 'ZONA ESTACIONAMIENTO VEHÍCULOS (CABO ROIG)', code: 'U0009', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0010', name: 'CANALIZACIÓN DE AGUA POTABLE (CABO ROIG)', code: 'U0010', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0011', name: 'CANALIZACIÓN DE DESAGÜE (CABO ROIG)', code: 'U0011', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0012', name: 'ACOMETIDA ELECTRICIDAD ENTRADA A EDIFICIOS (CABO ROIG)', code: 'U0012', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0013', name: 'CANALIZACIÓN DE ILUMINACIÓN EXTERIOR (CABO ROIG)', code: 'U0013', unit: 'USAC', hasBoiler: false },
  { id: 'CABO_U0014', name: 'CANALIZACIÓN DE TELECOMUNICACIONES (CABO ROIG)', code: 'U0014', unit: 'USAC', hasBoiler: false },

  // PANTEÓN MILITAR
  { id: 'PANT_I0001', name: 'PANTEÓN', code: 'I0001', unit: 'USAC', hasBoiler: false },
  { id: 'PANT_I0002', name: 'OSARIO', code: 'I0002', unit: 'USAC', hasBoiler: false },
];
