
import { OCACertificate } from '../types';
import { ALL_BUILDINGS } from './buildingsData';

const getBN = (id: string) => ALL_BUILDINGS.find(b => b.id === id)?.name || id;

export const OCA_SEEDS: OCACertificate[] = [
  // 1. PETROLÍFERAS
  {
    id: 'oca-001',
    title: 'Caldera D-64-E (Antiguo 121)',
    category: 'Petrolíferas',
    buildingId: 'E0064',
    buildingName: getBN('E0064'),
    installation: 'Petrolífera',
    denomination: 'Caldera D-64-E (ANTIGUO 121)',
    legislation: 'Real Decreto 1523/1999 (ITC MI-IP03)',
    capacity: '4990 litros',
    industryRegistrationDate: '18/05/2009',
    inspectionType: 'Revisión Anual',
    frequency: '1 AÑO',
    lastInspectionDate: '2025-02-13',
    expirationDate: '2026-02-13',
    periodicityYears: 1,
    type: 'EM',
    isSectorial: true,
    maintenanceCompany: 'TÉRMICAS',
    status: 'vigente'
  },
  {
    id: 'oca-002',
    title: 'Depósito Enterrado A',
    category: 'Petrolíferas',
    buildingId: 'E0068',
    buildingName: getBN('E0068'),
    installation: 'Petrolífera',
    denomination: 'DEPÓSITO ENTERRADO',
    legislation: 'Real Decreto 1523/1999 (ITC MI-IP03)',
    capacity: '5000 litros',
    industryRegistrationDate: '12/09/2016',
    inspectionType: 'Revisión Anual',
    frequency: '1 AÑO',
    lastInspectionDate: '2025-02-13',
    expirationDate: '2026-02-13',
    periodicityYears: 1,
    type: 'EM',
    isSectorial: true,
    maintenanceCompany: 'TÉRMICAS',
    status: 'vigente'
  },
  {
    id: 'oca-003',
    title: 'Prueba Estanqueidad Depósito E0068',
    category: 'Petrolíferas',
    buildingId: 'E0068',
    buildingName: getBN('E0068'),
    installation: 'Petrolífera',
    denomination: 'DEPÓSITO ENTERRADO',
    legislation: 'Real Decreto 1523/1999 (ITC MI-IP03)',
    capacity: '5000 litros',
    industryRegistrationDate: '12/09/2016',
    inspectionType: 'Prueba de Estanqueidad',
    frequency: '10 AÑOS',
    lastInspectionDate: '2016-02-16',
    expirationDate: '2026-02-16',
    periodicityYears: 10,
    type: 'EM/OCA',
    isSectorial: true,
    maintenanceCompany: 'TÉRMICAS',
    status: 'vigente'
  },
  {
    id: 'oca-004',
    title: 'Caldera C-042',
    category: 'Equipos a Presión',
    buildingId: 'E0042',
    buildingName: getBN('E0042'),
    installation: 'Equipos a Presión',
    denomination: 'CALDERA C-042',
    legislation: 'Orden 809/2021',
    capacity: '> 70 Kw',
    industryRegistrationDate: '2008-05-26',
    inspectionType: 'Inspección Periódica Nivel B',
    frequency: '3 AÑOS',
    lastInspectionDate: '2023-04-27',
    expirationDate: '2026-04-27',
    periodicityYears: 3,
    type: 'OCA',
    isSectorial: true,
    maintenanceCompany: 'TÉRMICAS',
    status: 'vigente'
  },
  {
    id: 'oca-005',
    title: 'Surtidor Gasolinera',
    category: 'Petrolíferas',
    buildingId: 'I0021',
    buildingName: 'GASOLINERA MOE',
    installation: 'Petrolífera',
    denomination: 'SURTIDOR GASOIL',
    legislation: 'Orden ITC/3720/2006',
    capacity: 'N/C',
    industryRegistrationDate: '2006-11-22',
    inspectionType: 'Revisión Periódica',
    frequency: '1 AÑO',
    lastInspectionDate: '2025-05-08',
    expirationDate: '2026-05-08',
    periodicityYears: 1,
    type: 'EM',
    isSectorial: false,
    maintenanceCompany: 'GERARDO LÓPEZ CASTILLO',
    status: 'vigente'
  },
  {
    id: 'oca-006',
    title: 'Grupo Electrógeno E0008',
    category: 'Baja Tensión',
    buildingId: 'E0008',
    buildingName: 'CUERPO DE GUARDIA',
    installation: 'Baja Tensión',
    denomination: 'GRUPO ELÉCTRICO E0008',
    legislation: 'Real Decreto 842/2002',
    capacity: '12 Kw (15 KVA)',
    industryRegistrationDate: 'N/C',
    inspectionType: 'Revisión Mantenimiento Anual',
    frequency: '1 AÑO',
    lastInspectionDate: '2025-05-19',
    expirationDate: '2026-05-19',
    periodicityYears: 1,
    type: 'EM',
    isSectorial: false,
    maintenanceCompany: 'GENIMANT',
    status: 'vigente'
  },
  {
    id: 'oca-007',
    title: 'Compresor Aire E0045',
    category: 'Equipos a Presión',
    buildingId: 'E0045',
    buildingName: '2º ESCALÓN DE MANTENIMIENTO MOE',
    installation: 'Equipos a Presión',
    denomination: 'COMPRESOR',
    legislation: 'Real Decreto 809/2021',
    capacity: '500 litros',
    industryRegistrationDate: 'N/C',
    inspectionType: 'Inspección Periódica Nivel B',
    frequency: '6 AÑOS',
    lastInspectionDate: '2019-11-04',
    expirationDate: '2025-11-04',
    periodicityYears: 6,
    type: 'OCA',
    isSectorial: false,
    maintenanceCompany: 'TECNO MECÁNICA 5',
    status: 'expirando'
  },
  {
    id: 'oca-008',
    title: 'LMT Interior',
    category: 'Media Tensión',
    buildingId: 'U0018',
    buildingName: 'CANALIZACIÓN MEDIA TENSIÓN',
    installation: 'LMT',
    denomination: 'LÍNEA MEDIA TENSIÓN INTERIOR',
    legislation: 'Real Decreto 223/2008',
    capacity: '20 KV',
    industryRegistrationDate: 'N/C',
    inspectionType: 'Inspección Periódica OCA',
    frequency: '3 AÑOS',
    lastInspectionDate: '2024-06-10',
    expirationDate: '2027-06-10',
    periodicityYears: 3,
    type: 'OCA',
    isSectorial: true,
    maintenanceCompany: 'GENIMANT',
    status: 'vigente'
  },
  {
    id: 'oca-009',
    title: 'Transformador CT 1',
    category: 'Transformadores',
    buildingId: 'CT_1_2',
    buildingName: 'TRANSFORMADOR CT 1',
    installation: 'Transformadores',
    denomination: 'TRANSFORMADOR TRIFÁSICO',
    legislation: 'Real Decreto 337/2014',
    capacity: '630 KVA',
    industryRegistrationDate: 'N/C',
    inspectionType: 'Inspección Periódica OCA',
    frequency: '3 AÑOS',
    lastInspectionDate: '2024-06-10',
    expirationDate: '2027-06-10',
    periodicityYears: 3,
    type: 'OCA',
    isSectorial: true,
    maintenanceCompany: 'GENIMANT',
    status: 'vigente'
  },
  {
    id: 'oca-010',
    title: 'Ascensor A-64',
    category: 'Ascensores',
    buildingId: 'E0064',
    buildingName: getBN('E0064'),
    installation: 'Ascensores',
    denomination: 'ASCENSOR A-64',
    legislation: 'Real Decreto 88/2013',
    capacity: 'N/C',
    industryRegistrationDate: '2008-01-11',
    inspectionType: 'Inspección Periódica',
    frequency: '2 AÑOS',
    lastInspectionDate: '2024-10-23',
    expirationDate: '2026-10-23',
    periodicityYears: 2,
    type: 'OCA',
    isSectorial: true,
    maintenanceCompany: 'OTIS',
    status: 'vigente'
  },

  // Generating the rest to reach ~101
  ...Array.from({ length: 91 }).map((_, i) => {
    const categories: OCACertificate['category'][] = [
      'Baja Tensión', 'Equipos a Presión', 'Petrolíferas', 
      'Climatización', 'Ascensores', 'Incendios', 'Gas', 
      'Pararrayos', 'LMT', 'Transformadores', 'Líneas de Vida'
    ];
    const cat = categories[i % categories.length];
    const bId = ALL_BUILDINGS[i % ALL_BUILDINGS.length]?.id || 'E0001';
    
    return {
      id: `oca-gen-${i + 11}`,
      title: `${cat} - Registro #${i + 11}`,
      category: cat,
      buildingId: bId,
      buildingName: getBN(bId),
      installation: 'Instalación General',
      denomination: `Elemento-${i + 11}`,
      legislation: 'RD Aplicable',
      capacity: 'N/C',
      industryRegistrationDate: '2015-01-01',
      inspectionType: i % 2 === 0 ? 'Inspección Periódica OCA' : 'Revisión Mantenimiento',
      frequency: i % 3 === 0 ? '5 AÑOS' : '1 AÑO',
      lastInspectionDate: '2025-01-15',
      expirationDate: i % 3 === 0 ? '2030-01-15' : '2026-01-15',
      periodicityYears: i % 3 === 0 ? 5 : 1,
      type: (i % 2 === 0 ? 'OCA' : 'EM') as any,
      isSectorial: i % 4 === 0,
      maintenanceCompany: i % 2 === 0 ? 'GENIMANT' : 'TÉRMICAS',
      status: 'vigente' as any
    } as OCACertificate;
  })
];
