
import { PhoneContact } from '../types';

const BOEL_XIX_SEEDS: Omit<PhoneContact, 'id'>[] = [
  { order: 1, unit: 'BOEL XIX', organization: 'JEFE BOEL XIX', role: 'TCOL JEFE BOEL XIX', employment: 'TCOL', name: 'MIGUEL', lastName: 'CRUZ PAÑERO', phone: '8347801', mobile: '636963619-8417801' },
  { order: 2, unit: 'BOEL XIX', organization: 'SUBOFICIALIA', role: 'SUBOFICIALIA', employment: 'SUB. MAYOR', name: 'JESUS JAVIER', lastName: 'MARCOS FERNÁNDEZ', phone: '8347802', mobile: '628091824-8414791' },
  { order: 3, unit: 'BOEL XIX', organization: 'SUBOFICIALIA', role: 'CABO MAYOR', employment: 'CABO MAYOR', name: 'OSCAR', lastName: 'JIMENEZ GOMEZ', phone: '8347802', mobile: '965237802' },
  { order: 4, unit: 'BOEL XIX', organization: 'SOSTENIMIENTO', role: 'JEFE ÁREA S1 / S4', employment: 'CTE.', name: 'SALVADOR', lastName: 'SARMIENTO MILLET', phone: '8347803', mobile: '620465947-8414795' },
  { order: 5, unit: 'BOEL XIX', organization: 'S-1 PERSONAL', role: 'JEFE S1', employment: 'STTE', name: 'FRANCISCO JAVIER', lastName: 'GIL DÍAZ', phone: '8347828', mobile: '661781799-8417469' },
  { order: 6, unit: 'BOEL XIX', organization: 'S-1 PERSONAL', role: 'AUXILIAR', employment: 'STTE', name: 'FELIPE', lastName: 'SORIANO GARCÍA', phone: '8347805', mobile: '' },
  { order: 7, unit: 'BOEL XIX', organization: 'S-1 PERSONAL', role: 'AUXILIAR', employment: 'CABO', name: 'NOELIA', lastName: 'MARTÍNEZ CANO', phone: '8347805', mobile: '' },
  { order: 8, unit: 'BOEL XIX', organization: 'S-1 PERSONAL', role: 'AUXILIAR', employment: 'CABO', name: 'FRANCISCO JAVIER', lastName: 'DA SILVA ÁLVAREZ', phone: '8347805', mobile: '' },
  { order: 9, unit: 'BOEL XIX', organization: 'S-2 INTELIGENCIA', role: 'JEFE S2', employment: 'CTE', name: 'GONZALO', lastName: 'ALEJANDRE TERROBA', phone: '8347804', mobile: '661778716 / 8417460' },
  { order: 10, unit: 'BOEL XIX', organization: 'S-2 INTELIGENCIA', role: 'SLPMC', employment: 'CABO MAYOR', name: 'EDUARDO', lastName: 'SALVADOR MORAGON', phone: '8347596', mobile: '' },
  { order: 11, unit: 'BOEL XIX', organization: 'S-2 INTELIGENCIA', role: 'AUXILIAR S2', employment: 'CAP', name: 'ANGEL', lastName: 'CASTRO JIMENEZ', phone: '8347810', mobile: '661779656-8417463' },
  { order: 12, unit: 'BOEL XIX', organization: 'S-3 OPERACIONES', role: 'JEFE AREA S3', employment: 'CTE', name: 'FRANCISCO JAVIER', lastName: 'VIGIL JIMENEZ', phone: '8347314', mobile: '' },
  { order: 13, unit: 'BOEL XIX', organization: 'S-3 OPERACIONES', role: 'JEFE S-33 OPERACIONES EN CURSO', employment: 'CAP', name: 'ADRIÁN', lastName: 'FUENTES GRANJA', phone: '8347529', mobile: '8414792' },
  { order: 14, unit: 'BOEL XIX', organization: 'S-3 OPERACIONES', role: 'AUX. S-33 OPERACIONES EN CURSO', employment: 'CABO MAYOR', name: 'ALEJANDRO', lastName: 'LOPEZ RODRIGUEZ MADRIDEJOS', phone: '8347808', mobile: '' },
  { order: 15, unit: 'BOEL XIX', organization: 'S-3 OPERACIONES', role: 'AUX-S33 OPERACIONES EN CURSO', employment: 'STTE', name: 'ANTONIO', lastName: 'CALVO DE CASTRO', phone: '8347808', mobile: '' },
  { order: 16, unit: 'BOEL XIX', organization: 'S-3 OPERACIONES', role: 'AUX-S33 OPERACIONES EN CURSO', employment: 'CABO', name: 'ADRIÁN', lastName: 'ESCÁMEZ CABALLERO', phone: '8347808', mobile: '' },
  { order: 17, unit: 'BOEL XIX', organization: 'S-4 LOGISTICA', role: 'JEFE S4', employment: 'CAP.', name: 'JOEL', lastName: 'CRUZ RODRÍGUEZ', phone: '8347819', mobile: '8414796' },
  { order: 18, unit: 'BOEL XIX', organization: 'S-4 LOGISTICA', role: 'AUXILIAR', employment: 'CABO', name: 'JOSE CARLOS', lastName: 'CASANOVA GARCIA', phone: '8347806', mobile: '' },
  { order: 19, unit: 'BOEL XIX', organization: 'S-4 LOGISTICA', role: 'AUXILIAR', employment: 'BG', name: 'LUIS', lastName: 'SANTIAGO DUQUE', phone: '8347806', mobile: '' },
  { order: 20, unit: 'BOEL XIX', organization: 'S-4 LOGISTICA', role: 'AUXILIAR', employment: 'CABO 1º', name: 'ISMAEL', lastName: 'HERNANDEZ SANMARTIN', phone: '8347806', mobile: '' },
  { order: 21, unit: 'BOEL XIX', organization: 'S-4 LOGISTICA', role: 'AUXILIAR', employment: 'SGTO 1º', name: 'SERGIO', lastName: 'ARTIME VÁZQUEZ', phone: '8347819', mobile: '965237819' },
  { order: 22, unit: 'BOEL XIX', organization: 'S-4 LOGISTICA', role: 'OPERADOR SIGLE', employment: 'CABO', name: 'ISRAEL', lastName: 'PÁEZ YAMUZA', phone: '8347831', mobile: '' },
  { order: 23, unit: 'BOEL XIX', organization: 'HABILITACION', role: 'HABILITACIÓN', employment: 'BG', name: 'JOSÉ ÁNGEL', lastName: 'MOTA SEPULVEDA', phone: '8347811', mobile: '661779569-8417462', email: 'jmotsep@et.mde.es' },
  { order: 24, unit: 'BOEL XIX', organization: 'HABILITACIÓN', role: 'AUXILIAR', employment: 'CABO 1º', name: 'ANTONIO', lastName: 'YÉLAMOS RIVILLAS', phone: '8347811', mobile: '' },
  { order: 25, unit: 'BOEL XIX', organization: 'MANDO Y PLM', role: 'JEFE ASAN', employment: 'CAP', name: 'JUAN', lastName: 'MORALES PEYRO', phone: '8347327', mobile: '', email: 'jmorpey@oc.mdef.es' },
  { order: 26, unit: 'BOEL XIX', organization: 'COE BOEL XIX', role: 'JEFE COE PLM', employment: 'CAP', name: 'ÁNGEL', lastName: 'CASTRO JIMÉNEZ', phone: '8347810', mobile: '' },
  { order: 27, unit: 'BOEL XIX', organization: 'COE BOEL XIX', role: 'AUXILIAR JECOE PLM', employment: 'CABO', name: 'SANTIAGO ISMAEL', lastName: 'GARCÍA GARCÍA', phone: '8347825', mobile: '' },
  { order: 28, unit: 'BOEL XIX', organization: 'COE BOEL XIX', role: 'JEFE SEAPO', employment: 'STTE', name: 'MANUEL', lastName: 'BARANGUÁ AZNAR', phone: '8347826', mobile: '661778739-8417461' },
  { order: 29, unit: 'BOEL XIX', organization: 'COE BOEL XIX', role: 'ALMACEN BOEL', employment: 'CABO', name: 'JOAQUIN', lastName: 'MARTINEZ CARRILLO', phone: '8347598', mobile: '' },
  { order: 30, unit: 'BOEL XIX', organization: 'COE BOEL XIX', role: 'ARMAMENTO BOEL XIX', employment: 'CABO 1º', name: 'JUAN', lastName: 'RUÍZ LÓPEZ', phone: '8347831', mobile: '' },
  { order: 31, unit: 'BOEL XIX', organization: 'SEC. TRANS.', role: 'JEFE SECC. TRANS.-CISPOC', employment: 'BG', name: 'JOSE RAMON', lastName: 'TUDELA JULBE', phone: '8347809', mobile: '' },
  { order: 32, unit: 'BOEL XIX', organization: 'SEC. TRANS.', role: 'BASE RADIO', employment: 'CABO 1º', name: 'YONATAN', lastName: 'GUTIÉRREZ LÓPEZ', phone: '8347832', mobile: '' },
  { order: 33, unit: 'BOEL XIX', organization: 'SEC. TRANS.', role: 'PARQUE TRANSMISIONES', employment: 'CABO 1º', name: 'RODRIGO ANDRÉS', lastName: 'BOTELLO VÁSQUEZ', phone: '8347827', mobile: '' },
  { order: 34, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'JEFE EO 91 MOV', employment: 'CAP.', name: 'IKER', lastName: 'MENDINUETA BERNARDOS', phone: '8347815', mobile: '661813650-8417464' },
  { order: 35, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'E.O.91 - MOV', employment: 'TTE', name: 'CRISITIAN', lastName: 'CORRALES GONZALEZ', phone: '8347791', mobile: '' },
  { order: 36, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'JEFE EO 92 MOV', employment: 'CAP', name: 'ESTEBAN', lastName: 'MARTINEZ SALAVADOR', phone: '8347792', mobile: '636976878-8417699' },
  { order: 37, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'E.O. 92 - MOV', employment: 'TTE', name: 'MARCOS', lastName: 'SIMÓN PARDOS', phone: '8347792', mobile: '' },
  { order: 38, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'JEFE E.O.93 - AGUA', employment: 'CAPITÁN', name: 'ALFONSO', lastName: 'MANSILLA RODRÍGUEZ', phone: '8347861', mobile: '620392892-8414797' },
  { order: 39, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'E.O. 93 - AGUA', employment: 'TTE', name: 'FABIO ANDREAS', lastName: 'PÉRAMO CARRIERE', phone: '8347796', mobile: '' },
  { order: 40, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'JEFE E.O.94 - APM', employment: 'CAP', name: 'JOSÉ MANUEL', lastName: 'VERDASCO MARTÍN', phone: '8347794', mobile: '690205698-8417441' },
  { order: 41, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'E.O.94 - APM', employment: 'TTE', name: 'GERMAN', lastName: 'MARTÍNEZ BARRIO', phone: '8347794', mobile: '' },
  { order: 42, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'JEFE E.O.95 - MONT', employment: 'CAP', name: 'JESÚS', lastName: 'MARTÍN ROURA', phone: '8347793', mobile: '620932587-8414793' },
  { order: 43, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'E.O.95 - MONT', employment: 'TTE', name: 'IGNACIO', lastName: 'ROMERO GARCÍA', phone: '8347793', mobile: '' },
  { order: 44, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'JEFE E.O.96 MOV', employment: 'CAP', name: 'JAIME DE LA SANTISIMA', lastName: 'URIARTE VEGA', phone: '8347845', mobile: '686645494-8419755' },
  { order: 45, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'E.O. 96 MOV', employment: 'TTE', name: 'PÉREZ GARCÍA', lastName: 'PEDRO', phone: '8347845', mobile: '' },
  { order: 46, unit: 'BOEL XIX', organization: 'E. OPERATIVOS', role: 'E.O.97 CAPAV', employment: 'TTE', name: 'JESÚS', lastName: 'FERNÁNDEZ RODRÍGUEZ', phone: '8347797', mobile: '661781457-8417466' },
  { order: 47, unit: 'BOEL XIX', organization: 'DEPENDENCIAS', role: 'PUERTAS DE ACCESO (EO,S Y PLMM)', employment: 'DEPENDENCIA', name: '.', lastName: '.', phone: '8347920', mobile: '' },
  { order: 48, unit: 'BOEL XIX', organization: 'DEPENDENCIAS', role: 'SERVICIO DE CUARTEL', employment: 'CABO 1º', name: 'DE SERVICIO', lastName: 'SUBOFICIAL', phone: '', mobile: '629910593-8417610' },
  { order: 49, unit: 'BOEL XIX', organization: 'DEPENDENCIAS', role: 'FAX BOEL XIX', employment: 'DEPENDENCIA', name: '', lastName: 'FAX BOEL XIX', phone: '8347828', mobile: '965237828' },
  { order: 50, unit: 'BOEL XIX', organization: 'DEPENDENCIAS', role: 'FAX BOEL XIX', employment: 'DEPENDENCIA', name: '', lastName: 'FAX BOEL XIX', phone: '8347828', mobile: '965237828' },
  { order: 51, unit: 'BOEL XIX', organization: 'S-3 OPERACIONES', role: 'JEFE S-35 OPERACIONES FUTURAS', employment: 'CAP', name: 'JAIME', lastName: 'DE LA TORRE LÓPEZ', phone: '8347807', mobile: '626422915-8414790' },
  { order: 52, unit: 'BOEL XIX', organization: 'S-3 OPERACIONES', role: 'AUX-S35 OPERACIONES FUTURAS', employment: '', name: '', lastName: '', phone: '8347529', mobile: '' },
  { order: 53, unit: 'BOEL XIX', organization: 'S-3 OPERACIONES', role: 'AUX-S35 OPERACIONES FUTURAS', employment: 'BG.', name: 'JOSÉ LUIS', lastName: 'PÉREZ-JUANA DÍAZ', phone: '8347807', mobile: '965237807' },
];

const USAC_SEEDS: Omit<PhoneContact, 'id'>[] = [
  { order: 1, unit: 'USAC', organization: 'JEFE USAC', role: 'JEFE USAC', name: '', lastName: '', phone: '8347851', mobile: '8417851' },
  { order: 2, unit: 'USAC', organization: 'USAC HABILITACION', role: 'HABILITACION', employment: 'STTE', name: 'JESUS PABLO', lastName: 'VÁZQUEZ GARCÍA', phone: '8347731', mobile: '' },
  { order: 3, unit: 'USAC', organization: 'S-2 INTELIGENCIA', role: 'S-2', employment: 'STTE', name: 'JOSÉ ANTONIO', lastName: 'NIEVA FERNÁNDEZ', phone: '8347744', mobile: '', email: 'jniefe2@et.mde.es' },
  { order: 4, unit: 'USAC', organization: 'RESIDENCIAS Y BARES', role: 'CAFETERÍA', employment: 'DEPENDENCIA', name: '.', lastName: 'CAFETERÍA DE ABAJO', phone: '8347742', mobile: '' },
  { order: 5, unit: 'USAC', organization: 'UNIDAD DE APOYO A UNIDADES', role: 'MEDIO AMBIENTE', employment: 'PCL', name: 'CARMELO', lastName: 'FRAGOSO IBÁÑEZ', phone: '8347798', mobile: '' },
  { order: 6, unit: 'USAC', organization: 'SERVICIOS DE ACTO', role: 'JEFE GUARDIA', employment: 'DEPENDENCIA', name: '.', lastName: 'JEFE GUARDIA', phone: '8347836', mobile: '' },
  { order: 7, unit: 'USAC', organization: 'SERVICIOS DE ACTO', role: 'SUBOFICIAL DE CUARTEL USAC', employment: 'DEPENDENCIA', name: '.', lastName: 'SUBOFICIAL DE CUARTEL USAC', phone: '636974988', mobile: '8417853' },
  { order: 8, unit: 'USAC', organization: 'SERVICIOS DE ACTO', role: 'OFICIAL DE CUARTEL MOE', employment: 'DEPENDENCIA', name: '.', lastName: 'OFICIAL DE CUARTEL MOE', phone: '8347834', mobile: '8417941' },
  { order: 9, unit: 'USAC', organization: 'SERVICIOS DE ACTO', role: 'CAPITAN DE CUARTEL', employment: 'CAP', name: '.', lastName: 'CAPITAN DE CUARTEL', phone: '636974490', mobile: '8417942' },
  { order: 10, unit: 'USAC', organization: 'S-1 PERSONAL', role: 'AUX S-1', employment: 'SDO', name: 'JUANA DE LA CRUZ', lastName: 'ARANEGA VILLAR', phone: '8347853', mobile: '' },
  { order: 11, unit: 'USAC', organization: 'OFICINA DE APOYO AL PERSONAL', role: 'FAX OFAP', employment: 'DEPENDENCIA', name: '.', lastName: 'FAX OFAP', phone: '8347743', mobile: '' },
  { order: 12, unit: 'USAC', organization: 'SERVICIOS DE ACTO', role: 'SERVICIO RELIGIOSO', employment: 'PATER', name: 'FRANCISCO JOSÉ', lastName: 'SIERRA VILCHEZ', phone: '8347799', mobile: '8414730' },
  { order: 13, unit: 'USAC', organization: 'S-4 LOGISTICA', role: 'SINFRADEF', employment: 'CABO 1º', name: 'JOSÉ ANGEL', lastName: 'MARTÍNEZ HERGUETA', phone: '8347745', mobile: '' },
  { order: 14, unit: 'USAC', organization: 'UNIDAD DE SEGURIDAD', role: 'OFICINA ACREDITACIONES', employment: 'CABO 1º', name: 'SANTIAGO IGNACIO', lastName: 'ARQUERO SANTOS', phone: '8347857', mobile: '' },
  { order: 15, unit: 'USAC', organization: 'UNIDAD DE SEGURIDAD', role: 'CAMARAS VIGILANCIA', employment: 'DEPENDENCIA', name: '.', lastName: 'CAMARAS VIGILANCIA', phone: '8347829', mobile: '' },
  { order: 16, unit: 'USAC', organization: 'ESTAFETA/REGISTTRO', role: 'AUXILIAR', employment: 'SOLDADO', name: 'JUAN JOSÉ', lastName: 'FUENTES RICO', phone: '8347693', mobile: '', email: 'jfueric@et.mde.es' },
  { order: 17, unit: 'USAC', organization: 'USAC DEPENDENCIAS', role: 'TIENDA EFECTOS MILITARES', employment: 'SRA.', name: 'SANDRA', lastName: '', phone: '8347846', mobile: '' },
  { order: 18, unit: 'USAC', organization: 'USAC DEPENDENCIAS', role: 'ASCENSOR RESIDENCIA', employment: 'DEPENDENCIA', name: '.', lastName: 'ASCENSOR RESIDENCIA', phone: '8347510', mobile: '' },
  { order: 19, unit: 'USAC', organization: 'UNIDAD DE SEGURIDAD', role: 'CONTROL ACCESO ACTO', employment: 'DEPENDENCIA', name: '.', lastName: 'CONTROL ACCESO ACTO', phone: '8347738', mobile: '' },
  { order: 20, unit: 'USAC', organization: 'UNIDAD DE SEGURIDAD', role: 'MANTO. CONTRAINCENDIOS', employment: 'CABO 1º', name: 'JOAQUÍN', lastName: 'ORTEGA PÉREZ', phone: '8347812', mobile: '' },
  { order: 21, unit: 'USAC', organization: 'USAC DEPENDENCIAS', role: 'PELUQUERÍA', employment: 'SRTA.', name: 'BELINDA', lastName: '', phone: '8347739', mobile: '' },
  { order: 22, unit: 'USAC', organization: 'UNIDAD DE APOYO INSTALACIONES', role: 'JEFE MANTENIMIENTO', employment: 'STTE', name: 'TOMAS', lastName: 'ZAMORA ESCLAPEZ', phone: '8347838', mobile: '8417925' },
  { order: 23, unit: 'USAC', organization: 'RESIDENCIAS Y BARES', role: 'OFICINA RESIDENCIA', employment: 'PCL', name: 'MARÍA CECILIA', lastName: 'LÓPEZ RUSO', phone: '8347843', mobile: '' },
  { order: 24, unit: 'USAC', organization: 'MANDO Y PLM', role: 'JEFE PLMM / JEFE SEGURIDAD', employment: '', name: '', lastName: '', phone: '8347546', mobile: '' },
  { order: 25, unit: 'USAC', organization: 'USAC HABILITACION', role: 'AUXILIAR HABILITACION', employment: 'CABO', name: 'JOSE JAVIER', lastName: 'GARCIA ESCUDERO', phone: '8347731', mobile: '' },
  { order: 26, unit: 'USAC', organization: 'UNIDAD DE APOYO AL PERSONAL', role: 'VEA / SETRE', employment: 'CABO 1º', name: 'ANGEL', lastName: 'MUÑOZ ABENGOZAR', phone: '8347839', mobile: '' },
  { order: 27, unit: 'USAC', organization: 'UNIDAD DE SEGURIDAD', role: 'JEFE UNIDAD DE SEGURIDAD', employment: 'STTE', name: 'JOSÉ ANTONIO', lastName: 'NIEVA FERNÁNDEZ', phone: '8347782', mobile: '' },
  { order: 28, unit: 'USAC', organization: 'S-4 LOGISTICA', role: 'AUX. S-4  LOGISTICA', employment: 'CABO', name: 'JOSÉ DANIEL', lastName: 'NADAL DEL ALAMO', phone: '8347856', mobile: '' },
  { order: 29, unit: 'USAC', organization: 'OFICINA DE APOYO AL PERSONAL', role: 'JEFE OFAP', employment: 'STTE', name: 'MANUEL', lastName: 'SERNA ALCARAZ', phone: '8347847', mobile: '' },
  { order: 30, unit: 'USAC', organization: 'SERVICIOS DE ACTO', role: 'COCINA', employment: 'DEPENDENCIA', name: 'ACUARTELAMIENTO', lastName: 'COCINA', phone: '8347750', mobile: '' },
  { order: 31, unit: 'USAC', organization: 'UNIDAD DE APOYO A UNIDADES', role: 'JEFE UNIDAD DE APOYO', employment: 'CAP', name: 'FERNANDO', lastName: 'MARTÍNEZ BLÁZQUEZ', phone: '8347852', mobile: '8417947' },
  { order: 32, unit: 'USAC', organization: 'U. APOYO A UNIDADES', role: 'JEFE MEDIO AMBIENTE', employment: 'STTE', name: 'PATRICIO', lastName: 'FUENTES MADRID', phone: '8347798', mobile: '' },
  { order: 33, unit: 'USAC', organization: 'OFICINA DE APOYO AL PERSONAL', role: 'OFAP', employment: 'CABO 1º', name: 'JOSÉ ALBERTO', lastName: 'FORTUNA CONCEJO', phone: '8347849', mobile: '' },
  { order: 34, unit: 'USAC', organization: 'OFICINA DE APOYO AL PERSONAL', role: 'OFAP', employment: 'CABO 1º', name: 'XAVIER', lastName: 'MELGUIZO TERRON', phone: '8347849', mobile: '' },
  { order: 35, unit: 'USAC', organization: 'SERVICIOS DE ACTO', role: 'JEFE SV EXTERNALIZADOS', employment: 'CABO MAYOR', name: 'ANDRES', lastName: 'PALOMARES MOUTOT', phone: '8347547', mobile: '8417855', email: 'apalmou@et.mde.es' },
  { order: 36, unit: 'USAC', organization: 'SERVICIOS DE ACTO', role: 'SUBOFICIAL DE SERVICIO MOE', employment: 'DEPENDENCIA', name: '.', lastName: 'SUBOFICIAL DE SERVICIO MOE', phone: '636998695', mobile: '8417940' },
  { order: 37, unit: 'USAC', organization: 'SERVICIOS DE ACTO', role: 'SV ALIMENTACION', employment: 'CABO 1º', name: 'RAÚL', lastName: 'MARTÍN DOMINGUEZ', phone: '8347547', mobile: '' },
  { order: 38, unit: 'USAC', organization: 'S-1 PERSONAL', role: 'AUXILIAR NEGOCIADO', employment: 'CABO 1º', name: 'MARCOS', lastName: 'REDONDO CASTAÑÓN', phone: '8347853', mobile: '' },
  { order: 39, unit: 'USAC', organization: 'S-3 OPERACIONES', role: 'S-3', employment: 'CABO', name: 'PABLO', lastName: 'ESCRIBANO LAGO', phone: '8347747', mobile: '' },
  { order: 40, unit: 'USAC', organization: 'UNIDAD DE APOYO A UNIDADES', role: 'OFICINA PRL', employment: 'CABO', name: 'MANUEL', lastName: 'MAZON GIL', phone: '8347784', mobile: '' },
  { order: 41, unit: 'USAC', organization: 'OFICINA DE APOYO AL PERSONAL', role: 'OFAP', employment: '', name: '', lastName: '', phone: '8347849', mobile: '' },
  { order: 42, unit: 'USAC', organization: 'ALOJAMIENTO LOGISTICO', role: 'JEFE ALOJAMIENTO LOGÍSTICO', employment: 'CABO', name: 'REINER', lastName: 'MONTESINOS BUTRÓN', phone: '8347854', mobile: '8417852' },
  { order: 43, unit: 'USAC', organization: 'U. DE APOYO INSTALACIONES', role: 'SC. MANTENIMIENTO', employment: '', name: '', lastName: '', phone: '', mobile: '' },
  { order: 44, unit: 'USAC', organization: 'UNIDAD DE APOYO AL PERSONAL', role: 'LAVANDERÍA', employment: 'SOLDADO', name: 'FRANCISCO JAVIER', lastName: 'GONZALEZ VERGARA', phone: '8347538', mobile: '' },
  { order: 45, unit: 'USAC', organization: 'UNIDAD DE APOYO AL PERSONAL', role: 'VEA / SETRE', employment: '', name: '', lastName: '', phone: '', mobile: '' },
  { order: 46, unit: 'USAC', organization: 'ALOJAMIENTO LOGÍSTICO', role: 'AUXILIAR', employment: 'DEPENDENCIA', name: 'MARIA CECILIA', lastName: 'LÓPEZ RUSO', phone: '8347844', mobile: '' },
  { order: 47, unit: 'USAC', organization: 'S-1 PERSONAL', role: 'JEFE NEGOCIADO', employment: 'STTE', name: 'JULIO', lastName: 'RUIZ MARTIN', phone: '', mobile: '' },
];


const ULOE_SEEDS: Omit<PhoneContact, 'id'>[] = [
  { order: 1, unit: 'ULOE', organization: 'JEFE ULOE', role: 'JEULOE', employment: 'TCOL', name: 'JUAN RAMON', lastName: 'HERRERA PEREZ', phone: '8347562', mobile: '8418155' },
  { order: 2, unit: 'ULOE', organization: 'SUBOFICIALIA', role: 'SBMY', employment: 'SBMY', name: 'JOSE ANTONIO', lastName: 'CHAHIN GARCIA', phone: '8347571', mobile: '' },
  { order: 3, unit: 'ULOE', organization: 'PLMM', role: 'JEFE POS', employment: 'CTE', name: 'MANUEL', lastName: 'MORA GARCIA', phone: '8347560', mobile: '8415780' },
  { order: 4, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'JEFE CIA MANDO Y SANIDAD', employment: 'CAP', name: 'SERGIO', lastName: 'FERNANDEZ MORA', phone: '8347588', mobile: '' },
  { order: 5, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUXILIAR DE CIA MANDO', employment: 'CBMY', name: 'MOISES', lastName: 'SANCHEZ ROSES', phone: '8347573', mobile: '' },
  { order: 10, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'JEFE POS PERSONAL', employment: 'BG', name: 'JOSE', lastName: 'FELIPE FLORES', phone: '8347567', mobile: '' },
  { order: 11, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX POS PERSONAL', employment: '', name: '', lastName: '', phone: '8347567', mobile: '' },
  { order: 12, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX POS PERSONAL', employment: 'CB 1º', name: 'JOSE ANTONIO', lastName: 'GONZALEZ CANO', phone: '8347567', mobile: '' },
  { order: 13, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX POS PERSONAL', employment: 'CBO', name: 'DAULFARY VIVIANA', lastName: 'MUNERA LOAIZA', phone: '8347567', mobile: '' },
  { order: 15, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'JEFE POS SEGURIDAD', employment: 'BG', name: 'MANUEL', lastName: 'ILLODO GONZALEZ', phone: '8347561', mobile: '' },
  { order: 16, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX POS SEGURIDAD', employment: 'SGT 1º', name: 'NELSON', lastName: 'MARTINEZ OCHOA', phone: '8347561', mobile: '' },
  { order: 17, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX POS SEGURIDAD', employment: 'CB 1º', name: 'MONICA', lastName: 'ROCAMORA BOSCHET', phone: '8347561', mobile: '' },
  { order: 21, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'JEFE POS OPERACIONES', employment: 'BG', name: 'JORGE', lastName: 'CONTRERAS PEREZ', phone: '8347570', mobile: '8415062' },
  { order: 22, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX POS OPERACIONES', employment: 'BG', name: 'CARLOS ENRIQUE', lastName: 'VICUÑA MONTALBAN', phone: '8347570', mobile: '' },
  { order: 26, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'CIS ULOE', employment: 'CBO', name: 'JONATAN LUIS', lastName: 'JIMENEZ MILLA', phone: '8347564', mobile: '' },
  { order: 30, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'SANIDAD', employment: 'STTE', name: 'JOSÉ VICENTE', lastName: 'YUSTE FERNANDEZ', phone: '8347579', mobile: '' },
  { order: 32, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'HABILITACIÓN', employment: 'BG', name: 'VICENTE', lastName: 'PORTERO CIMADEVILA', phone: '8347566', mobile: '' },
  { order: 33, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'HABILITACION', employment: 'CBO', name: 'JORGE', lastName: 'LEAL CORTES', phone: '8347566', mobile: '' },
  { order: 34, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'JEFE CICAL', employment: 'CTE', name: 'OSCAR', lastName: 'LEYVA CRIADO', phone: '8347310', mobile: '' },
  { order: 35, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'CICAL DIRECCION', employment: 'CAP', name: 'MARCO', lastName: 'BONELLI CHICHIZOLA', phone: '8347307', mobile: '' },
  { order: 36, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'JEFE CICAL ABASTO', employment: 'STTE', name: 'RODRIGO', lastName: 'LOSUA IRURETAGOYENA', phone: '8347572', mobile: '' },
  { order: 37, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX CICAL ABASTO', employment: 'BG', name: 'LORENA', lastName: 'FERNANDEZ MARTIN', phone: '8347572', mobile: '' },
  { order: 39, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'S-4', employment: 'STTE', name: 'JAVIER', lastName: 'GARCIA RAMIREZ', phone: '8347879', mobile: '' },
  { order: 40, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'JEFE CICAL MANTO', employment: 'STTE', name: 'EMILIO RUBEN', lastName: 'RODRIGUEZ BARCENA', phone: '8347580', mobile: '' },
  { order: 41, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX CICAL MANTO', employment: 'CB 1º', name: 'DIEGO JOSE', lastName: 'PEIRO PEREZ', phone: '8347578', mobile: '' },
  { order: 41, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'CICAL SANIDAD', employment: 'CB 1º', name: 'DIEGO JOSE', lastName: 'PEIRO PEREZ', phone: '8347578', mobile: '' },
  { order: 42, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'JEFE CICAL TRANSPORTES', employment: 'CB 1º', name: 'DIEGO', lastName: 'SUAREZ SORIANO', phone: '8347569', mobile: '' },
  { order: 43, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX CICAL TRANSPORTES', employment: 'CB 1º', name: 'DIEGO', lastName: 'SUAREZ SORIANO', phone: '8347569', mobile: '' },
  { order: 45, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'JEFE OTA', employment: 'CAP', name: 'SERGIO', lastName: 'FERNANDEZ MORA', phone: '8347588', mobile: '' },
  { order: 46, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX DE ADQUISICIONES', employment: 'STTE', name: 'JUAN DE DIOS', lastName: 'JIMENEZ PEÑARROYA', phone: '8347304', mobile: '' },
  { order: 47, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'OTA', employment: 'STTE', name: 'DAVID', lastName: 'CERRILLO CARRETERO', phone: '8347535', mobile: '' },
  { order: 48, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX DE ADQUISICIONES', employment: 'BG', name: 'RAUL', lastName: 'RIVILLA GALACHE', phone: '8347785', mobile: '' },
  { order: 49, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX OTA', employment: '', name: '', lastName: '', phone: '8347304', mobile: '' },
  { order: 50, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'CATALOGACIONES OTA', employment: 'STTE', name: 'JOSE JESUS', lastName: 'MARTINEZ CARRILLO', phone: '8347587', mobile: '' },
  { order: 51, unit: 'ULOE', organization: 'CIA MANDO Y SANIDAD', role: 'AUX OTA', employment: 'CBO', name: 'MIGUEL ANGEL', lastName: 'MARTINEZ MORANTE', phone: '8347681', mobile: '' },
  { order: 55, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: 'JEFE CIA MANTO', employment: 'CAP', name: 'JUAN JOSE', lastName: 'VIDAL RUIZ', phone: '8347345', mobile: '' },
  { order: 55, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: 'JEFE SECCION MANTENIMIENTO MOVIL', employment: 'TTE', name: 'JORGE LUIS', lastName: 'ALBARRAN LATORRE', phone: '8347901', mobile: '' },
  { order: 56, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: 'JEFE SECCION TECNICA DE MANTENIMIENTO', employment: 'TTE', name: 'IVAN', lastName: 'RIOS GONZALEZ', phone: '8347901', mobile: '' },
  { order: 57, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: 'AUX CIA MANTENIMIENTO', employment: 'BG', name: 'MIGUEL', lastName: 'SUAREZ CORTES', phone: '8347312', mobile: '' },
  { order: 58, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: 'AUX CIA MANTENIMIENTO', employment: 'SGT 1º', name: 'ANDRES', lastName: 'LOPEZ SANCHEZ', phone: '8347312', mobile: '' },
  { order: 59, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: 'OF TECNICA', employment: 'STTE', name: 'SIGFREDO', lastName: 'PEREZ VINUESA', phone: '8347664', mobile: '' },
  { order: 60, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: 'ALMACEN CLASE IX', employment: 'SGT 1º', name: 'LUIS', lastName: 'DE RADA MONIZ', phone: '8347781', mobile: '' },
  { order: 61, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: 'RECEPCION Y ENTREGA', employment: 'CB 1º', name: 'ADOLFO', lastName: 'BADIA REAL', phone: '8347783', mobile: '' },
  { order: 62, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: '2º ESCALON ARMAMENTO', employment: 'SGT 1º', name: 'FRANCISCO DANIEL', lastName: 'CONEJERO MEDINA', phone: '8347662', mobile: '' },
  { order: 63, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: '2º ESC OPTICA Y ELECTRONICA', employment: 'BG', name: 'JESÚS MANUEL', lastName: 'GAMONAL CARRASCO', phone: '8347668', mobile: '' },
  { order: 64, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: '2º ESC TRANSMISIONES', employment: 'SGT 1º', name: 'JULIO DAVID', lastName: 'BAENA MORENO', phone: '8347663', mobile: '' },
  { order: 65, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: '2º ESC CHAPA Y PINTURA', employment: 'BG', name: 'MAYTE', lastName: 'DE JESUS SANCHEZ', phone: '8347671', mobile: '' },
  { order: 66, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: 'TALLER 3D', employment: 'SGT 1º', name: 'ABEL', lastName: 'PASCUAL HARO', phone: '8347642', mobile: '' },
  { order: 67, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: '2º ESC AUTOMOCION PESADOS', employment: 'SGT 1º', name: 'FRANCISCO JOSE', lastName: 'VERA GOMEZ', phone: '8347660', mobile: '' },
  { order: 68, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: '2º ESC VEHICULOS LIGEROS', employment: 'SGT 1º', name: 'LEOPOLDO', lastName: 'LEVET ALZAGA', phone: '8347321', mobile: '' },
  { order: 69, unit: 'ULOE', organization: 'CIA MANTENIMIENTO', role: '2º ESC MAQUINAS Y EQUIPOS', employment: 'SGTO', name: 'SANTIAGO', lastName: 'NAVARRO BELLOD', phone: '8347703', mobile: '' },
  { order: 75, unit: 'ULOE', organization: 'CIA ABASTECIMIENTO', role: 'JEFE ABASTECIMIENTO', employment: 'CAP', name: 'BORJA', lastName: 'FERNANDEZ BRIZ', phone: '8347576', mobile: '8407019' },
  { order: 76, unit: 'ULOE', organization: 'CIA ABASTECIMIENTO', role: 'JEFE SC ABASTECIMIENTO CLASE I-II-IV-VI-VIII', employment: 'TTE', name: 'JUAN', lastName: 'RUBIO TAUSTE', phone: '8347862', mobile: '' },
  { order: 76, unit: 'ULOE', organization: 'CIA ABASTECIMIENTO', role: 'JEFE SC ABASTECIMIENTO CLASE III- V-VII / PLN', employment: 'TTE', name: 'JOSE MANUEL', lastName: 'RAIGAL LOPEZ', phone: '8347332', mobile: '' },
  { order: 77, unit: 'ULOE', organization: 'CIA ABASTECIMIENTO', role: 'JEFE PN V-VII', employment: 'SGT 1º', name: 'ALBERTO', lastName: 'DIAZ INCERTI', phone: '8347574', mobile: '' },
  { order: 78, unit: 'ULOE', organization: 'CIA ABASTECIMIENTO', role: 'AUX PLM ABASTECIMIENTO', employment: 'CBMY', name: 'GABRIEL ANGEL', lastName: 'POL ROMAN', phone: '8347306', mobile: '' },
  { order: 79, unit: 'ULOE', organization: 'CIA ABASTECIMIENTO', role: 'ARMERIA', employment: 'CBO', name: 'JOSE MANUEL', lastName: 'PEREZ ESCALADA', phone: '8347568', mobile: '' },
  { order: 80, unit: 'ULOE', organization: 'CIA ABASTECIMIENTO', role: 'OFICINA ALMACEN', employment: 'STTE', name: 'JUAN FRANCISCO', lastName: 'MUÑOZ MULA', phone: '8347666', mobile: '' },
  { order: 81, unit: 'ULOE', organization: 'CIA ABASTECIMIENTO', role: 'AUX OFICINA ALMACEN', employment: 'CBO', name: 'TATIANA', lastName: 'LUPERCIO QUINDE', phone: '8347788', mobile: '' },
  { order: 85, unit: 'ULOE', organization: 'SECCION TRANSPORTES', role: 'JEFE SECCION TRANSPORTES', employment: 'STTE', name: 'JUAN ANGEL', lastName: 'REAL REAL', phone: '8347575', mobile: '8418713' },
  { order: 86, unit: 'ULOE', organization: 'SECCION TRANSPORTES', role: 'AUX SECCION TRANSPORTES', employment: 'CBMY', name: 'ISMAEL', lastName: 'RIQUELME IBAÑEZ', phone: '8347305', mobile: '' },
  { order: 87, unit: 'ULOE', organization: 'SECCION TRANSPORTES', role: 'PN TRANSPORTE PESADO', employment: 'CB 1º', name: 'DAVID', lastName: 'ALBEROLA ANDREU', phone: '8347661', mobile: '' },
  { order: 88, unit: 'ULOE', organization: 'SECCION TRANSPORTES', role: 'PN TRANSPORTE MEDIO/LIGERO', employment: 'CB 1º', name: 'RAMON', lastName: 'FERNANDEZ QUILES', phone: '8347661', mobile: '' },
  { order: 95, unit: 'ULOE', organization: 'UEXP', role: 'JEFE UNIDAD DE EXPERIENCIAS', employment: '', name: '', lastName: '', phone: '8347677', mobile: '628164862' },
  { order: 96, unit: 'ULOE', organization: 'UEXP', role: 'ANALISTA UNIDAD DE EXPERIENCIAS', employment: 'STTE', name: 'LUIS', lastName: 'FERNANDEZ REGIDOR', phone: '8347669', mobile: '' },
  { order: 97, unit: 'ULOE', organization: 'UEXP', role: 'ANALISTA UNIDAD DE EXPERIENCIAS', employment: 'BG', name: 'RAFAEL', lastName: 'MESTRES VALENTI', phone: '', mobile: '' },
  { order: 98, unit: 'ULOE', organization: 'UEXP', role: 'ANALISTA UNIDAD DE EXPERIENCIAS', employment: 'CB 1º', name: 'SERGIO', lastName: 'CARRUCHENO SANCHEZ', phone: '8347669', mobile: '' },
  { order: 99, unit: 'ULOE', organization: 'UEXP', role: 'AUX UNIDAD DE EXPERIENCIAS', employment: '', name: '', lastName: '', phone: '8347669', mobile: '' },
  { order: 100, unit: 'ULOE', organization: 'ESCON', role: 'JEFE ESCUELA CONDUCTORES', employment: 'STTE', name: 'JUAN ANTONIO', lastName: 'BAENA POLO', phone: '8347842', mobile: '' },
  { order: 101, unit: 'ULOE', organization: 'ESCON', role: 'AUX ESCUELA DE CONDUCTORES', employment: 'BG', name: 'MIGUEL', lastName: 'MARTINEZ MOLINER', phone: '8347842', mobile: '' },
  { order: 102, unit: 'ULOE', organization: 'DEPENDENCIAS', role: 'CABO 1º CUARTEL', employment: 'CB 1º', name: '.', lastName: '.', phone: '8415795', mobile: '620735795' },
];


const SVC_SANITARIO_SEEDS: Omit<PhoneContact, 'id'>[] = [
  { order: 1, unit: 'SVC SANITARIO', organization: 'BOTIQUÍN', role: 'JEFE DE SANIDAD', employment: 'TTE', name: 'IGNACIO BERNARDO', lastName: 'POLADURA HERNANDEZ', phone: '8347699', mobile: '8417971', email: 'ipolher@mde.es' },
  { order: 2, unit: 'SVC SANITARIO', organization: 'BOTIQUÍN', role: '2º MÉDICO CG', employment: 'TTE', name: 'MARTA', lastName: 'ALEJO ARANDA', phone: '8347841', mobile: '', email: 'maleara@mde.es' },
  { order: 3, unit: 'SVC SANITARIO', organization: 'BOTIQUIN', role: 'ADMINISTRACIÓN', employment: 'SOLDADO', name: '', lastName: '', phone: '8347840', mobile: '' },
  { order: 4, unit: 'SVC SANITARIO', organization: 'BOTIQUIN', role: 'SERVICIO DE ODONTOLOGIA', employment: 'CTE', name: 'SERGIO', lastName: 'SÁNCHEZ RODRÍGUEZ', phone: '8347741', mobile: '', email: 'ssanro8@oc.mde.es' },
  { order: 5, unit: 'SVC SANITARIO', organization: 'BOTIQUÍN', role: 'GABINETE DE PSICOLOGIA', employment: 'CAP', name: 'DOLORES MARTA', lastName: 'TONDA MUÑOZ', phone: '8347748', mobile: '', email: 'dtonmun@et.mde.es' },
  { order: 6, unit: 'SVC SANITARIO', organization: 'BOTIQUÍN', role: 'JEFE ENFERMERÍA', employment: 'CAP', name: 'JUAN', lastName: 'MORALES PEYRO', phone: '8347330', mobile: '', email: 'jmorpey@oc.mde.es' },
  { order: 7, unit: 'SVC SANITARIO', organization: 'GCG SERVICIO SANITARIO', role: 'SERVICIO SANITARIO ENFERMERIA', employment: 'TTE', name: 'ISABEL', lastName: 'GALÁN CÓRDOBA', phone: '8347313', mobile: '', email: 'igalcor@mde.es' },
  { order: 8, unit: 'SVC SANITARIO', organization: 'GOE III SERVICIO SANITARIO', role: 'SERVICIO SANITARIO ENFERMERIA', employment: 'CAP', name: 'RODRIGO', lastName: 'SANTOS GÓMEZ', phone: '8347531', mobile: '', email: 'rsang30@mde.es' },
  { order: 9, unit: 'SVC SANITARIO', organization: 'GOE III SERVICIO SANITARIO', role: 'SERVICIO SANITARIO ENFERMERIA', employment: 'TTE', name: 'LORENA', lastName: 'CATALÁN GUARCH', phone: '8347531', mobile: '', email: 'lcatgua@mde.es' },
  { order: 10, unit: 'SVC SANITARIO', organization: 'BOEL XIX SERVICIO SANITARIO', role: 'SERVICIO SANITARIO ENFERMERIA', employment: 'CAP', name: 'JUAN', lastName: 'MORALES PEYRO', phone: '8347805', mobile: '', email: 'jmorpey@oc.mde.es' },
  { order: 11, unit: 'SVC SANITARIO', organization: 'BOEL XIX SERVICIO SANITARIO', role: 'SERVICIO SANITARIO ENFERMERIA', employment: 'CAP', name: 'DEBORA', lastName: 'RODRIGUEZ NOVOA', phone: '8347805', mobile: '', email: 'drodnov@mde.es' },
  { order: 12, unit: 'SVC SANITARIO', organization: 'GOE IV SERVICIO SANITARIO', role: 'SERVICIO SANITARIO ENFERMERIA', employment: 'CAP', name: 'NATHALIE', lastName: 'LÁZARO BASHILE', phone: '8347749', mobile: '', email: 'nlazbas@oc.mde.es' },
  { order: 13, unit: 'SVC SANITARIO', organization: 'GOE IV SERVICIO SANITARIO', role: 'SERVICIO SANITARIO ENFERMERIA', employment: 'CAP', name: 'FRANCISCO ANDRÉS', lastName: 'NAVALÓN ALFARO', phone: '8347749', mobile: '', email: 'fnavalf@mde.es' },
  { order: 14, unit: 'SVC SANITARIO', organization: 'ULOE SERVICIO SANITARIO', role: 'SERVICIO SANITARIO ENFERMERIA', employment: 'TTE', name: 'ALICIA', lastName: 'ORTIZ DOMINGO', phone: '8347749', mobile: '', email: 'aortdom@mde.es' },
  { order: 15, unit: 'SVC SANITARIO', organization: 'ULOE SERVICIO SANITARIO', role: 'SERVICIO SANITARIO ENFERMERIA', employment: 'TTE', name: 'VICTOR', lastName: 'PORRAS DIAZ', phone: '8347749', mobile: '', email: 'vpordia@mde.es' },
  { order: 16, unit: 'SVC SANITARIO', organization: 'USAC SERVICIO SANITARIO', role: 'SERVICIO SANITARIO', employment: '', name: '', lastName: '', phone: '8347612', mobile: '' },
];


const GOE_IV_SEEDS: Omit<PhoneContact, 'id'>[] = [
  { order: 1, unit: 'GOE IV', organization: 'JEFE GOE IV', role: 'JEFE GOE IV', employment: 'TCOL', name: 'ALBERTO', lastName: 'MARTIN CALVO', phone: '8347751', mobile: '690202765', email: 'amarca4@et.mde.es' },
  { order: 2, unit: 'GOE IV', organization: 'MANDO Y PLM', role: 'SUBOFICIAL MAYOR', employment: 'SUB. MAYOR', name: 'FRANCISCO JAVIER', lastName: 'CHACON MORO', phone: '8347502', mobile: '', email: 'fchamor@et.mde.es' },
  { order: 3, unit: 'GOE IV', organization: 'MANDO Y PLM', role: 'SECRETARIO', employment: 'CABO MAYOR', name: 'NICOLÁS', lastName: 'LOZANO MORALES', phone: '8347753', mobile: '', email: 'nlozmor@et.mde.es' },
  { order: 4, unit: 'GOE IV', organization: 'S-1 PERSONAL', role: 'S1 JEFE', employment: 'BG', name: 'RAÚL', lastName: 'PÉREZ MARTÍN', phone: '8347759', mobile: '', email: 'rperma5@et.mde.es' },
  { order: 5, unit: 'GOE IV', organization: 'S-1 PERSONAL', role: 'S1 AUX2', employment: 'CABO MAYOR', name: 'ANTONIO', lastName: 'MARIN IGLESIAS', phone: '8347759', mobile: '', email: 'amarigl@et.mde.es' },
  { order: 6, unit: 'GOE IV', organization: 'S-1 PERSONAL', role: 'S1 AUX3', employment: 'CBO 1º', name: 'JOSE', lastName: 'PÉREZ BRETONES', phone: '8347756', mobile: '', email: 'jperbre@et.mde.es' },
  { order: 7, unit: 'GOE IV', organization: 'S-2 INTELIGENCIA', role: 'S2 JEFE', employment: 'CTE', name: 'EDUARDO JOSE', lastName: 'DE LA CAMARA CAMPAÑA', phone: '8347761', mobile: '661772889', email: 'edelcam@mde.es' },
  { order: 8, unit: 'GOE IV', organization: 'S2- INTELIGENCIA', role: 'S2 AUX 1', employment: 'CAP', name: 'JUAN', lastName: 'RECIO IBAÑEZ', phone: '8347761', mobile: '', email: 'jreciba@mde.es' },
  { order: 9, unit: 'GOE IV', organization: 'S-2 INTELIGENCIA', role: 'CI/SEG', employment: 'BG', name: 'JOSE', lastName: 'FOLLA LOPEZ', phone: '8347761', mobile: '', email: 'jfollop@et.mde.es' },
  { order: 10, unit: 'GOE IV', organization: 'S-2 INTELIGENCIA', role: 'SLPMC', employment: 'CABO MAYOR', name: 'DAVID', lastName: 'GIL ALVAREZ', phone: '8347766', mobile: '', email: 'dgilalv@et.mde.es' },
  { order: 11, unit: 'GOE IV', organization: 'MANDO Y PLM', role: 'JEFE SOSTENIMIENTO', employment: 'CAP', name: 'DIEGO', lastName: 'CUESTA HERNANDEZ', phone: '8347777', mobile: '', email: 'dcueher@mde.es' },
  { order: 12, unit: 'GOE IV', organization: 'MANDO Y PLM', role: 'JEFE DE OPERACIONES', employment: 'CTE', name: 'RAFAEL EDUARDO', lastName: 'MENENDEZ DIAZ', phone: '8347758', mobile: '661762155', email: 'rmendi1@mde.es' },
  { order: 13, unit: 'GOE IV', organization: 'S-5 PLANES', role: 'AUX - S35', employment: 'CAP', name: 'JESUS', lastName: 'NOVO GONZALEZ', phone: '8347316', mobile: '626048433', email: 'jnovgon@mde.es' },
  { order: 14, unit: 'GOE IV', organization: 'S-5 PLANES', role: 'S5 AUX 1', employment: 'STTE', name: 'FRANCISCO', lastName: 'GOMEZ LINARES', phone: '8347316', mobile: '', email: 'fgomlin@et.mde.es' },
  { order: 15, unit: 'GOE IV', organization: 'S-5 PLANES', role: 'S5 AUX 2', employment: 'BG', name: 'JOSE ISMAEL', lastName: 'BLAZQUEZ MUÑOZ', phone: '8347316', mobile: '', email: 'jblamu1@ea.mde.es' },
  { order: 16, unit: 'GOE IV', organization: 'S-3 OPERACIONES', role: 'S3 OPSCUR AUX 2', employment: 'STTE', name: 'ESMERALDA', lastName: 'RUIZ ALONSO', phone: '8347760', mobile: '', email: 'eruialo@et.mde.es' },
  { order: 17, unit: 'GOE IV', organization: 'S-3 OPERACIONES', role: 'S3 OPSCUR AUX 1', employment: 'SGT1º', name: 'CARLOS', lastName: 'RAMIREZ GUERRA', phone: '8347775', mobile: '', email: 'cramgue@mde.es' },
  { order: 18, unit: 'GOE IV', organization: 'S-3 OPERACIONES', role: 'S3 OPSCUR AUX 3', employment: 'BG', name: 'TOMAS', lastName: 'CANTO CANO', phone: '8347768', mobile: '', email: 'tcancan@mde.es' },
  { order: 19, unit: 'GOE IV', organization: 'S-4 LOGISTICA', role: 'TRANSPORTES', employment: 'CBO 1º', name: 'JAVIER', lastName: 'GOMEZ RODRIGUEZ', phone: '8347767', mobile: '', email: 'jgomr18@mde.es' },
  { order: 20, unit: 'GOE IV', organization: 'S-4 LOGISTICA', role: 'ARMAMENTO', employment: 'CBO 1º', name: 'MANUEL JOSE', lastName: 'RIVEIRO MARIÑO', phone: '8347779', mobile: '', email: 'mrivmar@et.mde.es' },
  { order: 21, unit: 'GOE IV', organization: 'S-4 LOGISTICA', role: 'JEFE SECCION APOYO', employment: 'STTE', name: 'JUAN CARLOS', lastName: 'VERDU TORREGROSA', phone: '8347764', mobile: '', email: 'jvertor@et.mde.es' },
  { order: 22, unit: 'GOE IV', organization: 'S-4 LOGISTICA', role: 'SIGLE', employment: 'CBO 1º', name: 'SERGIO', lastName: 'FERRÁNDEZ GARCÍA', phone: '8347773', mobile: '', email: 'sferga1@et.mde.es' },
  { order: 23, unit: 'GOE IV', organization: 'S-4 LOGISTICA', role: 'SIGLE', employment: 'SDO', name: 'MIGUEL', lastName: 'DOMENECH MADRIGAL', phone: '8347755', mobile: '', email: 'mdommad@mde.es' },
  { order: 24, unit: 'GOE IV', organization: 'S-4 LOGISTICA', role: 'SIGLE', employment: 'CBO', name: 'VICTOR', lastName: 'CASTELLÓ SANCHEZ', phone: '8347755', mobile: '', email: 'vcassan@mde.es' },
  { order: 25, unit: 'GOE IV', organization: 'S-4 LOGISTICA', role: 'S-4', employment: 'C1º', name: 'ENRIQUE', lastName: 'BALADA PEREZ', phone: '8347764', mobile: '', email: 'ebalpe1@mde.es' },
  { order: 26, unit: 'GOE IV', organization: 'S-4 LOGISTICA', role: 'ABASTECIMIENTO', employment: 'CBO', name: 'JESÚS', lastName: 'HERNÁNDEZ PUJANTE', phone: '8347763', mobile: '', email: 'jherpuj@mde.es' },
  { order: 27, unit: 'GOE IV', organization: 'DEPENDENCIAS', role: 'ARMERIA', employment: 'CBO 1º', name: 'MANUEL JOSE', lastName: 'RIVEIRO MARIÑO', phone: '8347860', mobile: '', email: 'mrivmar@et.mde.es' },
  { order: 28, unit: 'GOE IV', organization: 'S-4 LOGISTICA', role: 'JEFE COE PLM', employment: 'CAP', name: 'ESTEBAN', lastName: 'GONZALEZ GONZALEZ', phone: '8347776', mobile: '', email: 'egongo6@mde.es' },
  { order: 29, unit: 'GOE IV', organization: 'SEC. TRANS.', role: 'JEFE SECCIÓN TRANS.', employment: 'SGTO 1º', name: 'CARLOS', lastName: 'AGUILAR SOTO', phone: '8347778', mobile: '', email: 'cagusot@et.mde.es' },
  { order: 30, unit: 'GOE IV', organization: 'SEC. TRANS.', role: 'CIS', employment: 'CBO', name: 'MIGUEL', lastName: 'PEREZ BARON', phone: '8347757', mobile: '', email: 'mperba5@et.mde.es' },
  { order: 31, unit: 'GOE IV', organization: 'SECC. TRANS', role: 'SEC. TRANSMISIONES', employment: 'CABO 1º', name: 'FRANCISCO MIGUEL', lastName: 'ALMANSA MAVIT', phone: '8347757', mobile: '', email: 'falmmav@et.mde.es' },
  { order: 32, unit: 'GOE IV', organization: 'SEC. TRANS.', role: 'SEC. TRANSMISIONES', employment: 'CABO 1º', name: 'GUILLERMO', lastName: 'PALOMARES MOUTOT', phone: '8347557', mobile: '', email: 'gpalmou@et.mde.es' }, // Corrected duplication or kept separate as per list
  { order: 33, unit: 'GOE IV', organization: 'SEC. TRANS.', role: 'PARQUE', employment: 'SDO', name: 'JORGE', lastName: 'MORALES LABRADO', phone: '8347754', mobile: '', email: 'jmorlab@mde.es' },
  { order: 33, unit: 'GOE IV', organization: 'HABILITACION', role: 'JEFE HABILITACION', employment: 'BG', name: 'RAFAEL', lastName: 'REVERT BELOQUI', phone: '8347765', mobile: '', email: 'rrevbel@et.mde.es' },
  { order: 34, unit: 'GOE IV', organization: 'DEPENDENCIAS', role: 'SERVICIOS SANITARIOS', employment: 'CAP', name: 'FRANCISCO ANDRES', lastName: 'NAVALON ALFARO', phone: '8347778', mobile: '', email: 'fnavalf@mde.es' },
  { order: 35, unit: 'GOE IV', organization: 'DEPENDENCIAS', role: 'CABO1º DE CUARTEL', employment: 'CABO 1º', name: '.', lastName: 'CABO 1º  DE CUARTEL', phone: '8417753', mobile: '636967674' },
  { order: 36, unit: 'GOE IV', organization: 'DEPENDENCIAS', role: 'SALA DE REUNIONES', employment: 'SALA', name: '.', lastName: 'REUNIONES', phone: '8347772', mobile: '' },
  { order: 37, unit: 'GOE IV', organization: 'E. OPERATIVOS', role: 'EO 41', employment: 'CAP', name: 'HECTOR', lastName: 'SOLANA GUERRERO', phone: '8347774', mobile: '661774954', email: 'hsolgue@mde.es' },
  { order: 38, unit: 'GOE IV', organization: 'E. OPERATIVOS', role: 'EO 42', employment: 'TTE', name: 'JAVIER', lastName: 'MARTINEZ SALAZAR', phone: '8347770', mobile: '620726150', email: 'jmars15@mde.es' },
  { order: 39, unit: 'GOE IV', organization: 'E. OPERATIVOS', role: 'EO 43', employment: 'CAP', name: 'ADRIAN', lastName: 'MARTINEZ RIAÑO', phone: '8347769', mobile: '661813635', email: 'ariamar@mde.es' },
  { order: 40, unit: 'GOE IV', organization: 'E. OPERATIVOS', role: 'EO 44', employment: 'CAP', name: 'ALBERTO', lastName: 'BARET HERNANDEZ', phone: '8347863', mobile: '620188752', email: 'mherri1@mde.es' },
  { order: 41, unit: 'GOE IV', organization: 'E. OPERATIVOS', role: 'EO 45', employment: 'CAP', name: 'ENRIQUE', lastName: 'RUBIO GARCIA', phone: '8347771', mobile: '661813642', email: 'erubga1@mde.es' },
  { order: 42, unit: 'GOE IV', organization: 'E. OPERATIVOS', role: 'EO 46', employment: 'CAP', name: 'RAMON IGNACIO', lastName: 'GOMEZ LASA', phone: '8347762', mobile: '661813646', email: 'rgomlas@mde.es' },
  { order: 43, unit: 'GOE IV', organization: 'E. OPERATIVOS', role: 'EOCA', employment: 'CAP', name: 'ALEJANDRO', lastName: 'JIMENEZ MARQUEZ', phone: '8347325', mobile: '661776778', email: 'ajimma2@mde.es' },
];


const GOE_III_SEEDS: Omit<PhoneContact, 'id'>[] = [
  { order: 1, unit: 'GOE III', organization: 'JEFE GOE III', role: 'JEFE GOE III', employment: 'TCOL', name: 'ANTONIO', lastName: 'RODRIGUEZ MARTINEZ', phone: '8347701', mobile: '8417701' },
  { order: 2, unit: 'GOE III', organization: 'MANDO Y PLM', role: 'SUB. MAYOR', employment: 'SUB. MAYOR', name: 'RAMON ESTEBAN', lastName: 'LUACES FERNANDEZ', phone: '8347702', mobile: '' },
  { order: 3, unit: 'GOE III', organization: 'MANDO Y PLM', role: 'SUBOFICIALIA', employment: 'CBO. MAYOR', name: 'LUIS', lastName: 'PERIRA ARIAS', phone: '8347702', mobile: '' },
  { order: 4, unit: 'GOE III', organization: 'S-1 PERSONAL', role: 'S-1 JEFE', employment: 'CAPITAN', name: 'JOAQUIN', lastName: 'PUIGCERVER SANCHO', phone: '8347319', mobile: '' },
  { order: 5, unit: 'GOE III', organization: 'S-1 PERSONAL', role: 'S-1 AUX', employment: 'SUB.TTE', name: 'AGUSTIN', lastName: 'SANZ MELIAN', phone: '8347708', mobile: '' },
  { order: 6, unit: 'GOE III', organization: 'S-1 PERSONAL', role: 'S-1', employment: 'CABO', name: 'HECTOR', lastName: 'FERRER GUILLEN', phone: '8347708', mobile: '' },
  { order: 7, unit: 'GOE III', organization: 'S-1 PERSONAL', role: 'S-1', employment: 'CABO', name: 'JAVIER', lastName: 'CESTERO HERAS', phone: '8347888', mobile: '' },
  { order: 8, unit: 'GOE III', organization: 'S1- HOJAS', role: 'S-1', employment: 'SDO', name: 'ANDRES', lastName: 'GONZALEZ NOGUER', phone: '8347543', mobile: '' },
  { order: 9, unit: 'GOE III', organization: 'S-2 JEFE', role: 'S-2 JEFE', employment: '', name: '', lastName: '', phone: '8347752', mobile: '' },
  { order: 10, unit: 'GOE III', organization: 'S-2 INTELIGENCIA', role: 'S-2 2º JEFE', employment: 'BRIGADA', name: 'GUSTAVO JORGE', lastName: 'FERNANDEZ MARTINEZ', phone: '8347707', mobile: '' },
  { order: 11, unit: 'GOE III', organization: 'S-2 INTELIGENCIA', role: 'S-2', employment: 'CABO 1º', name: 'DAVID', lastName: 'MENDEZ MARTIN', phone: '8347707', mobile: '' },
  { order: 12, unit: 'GOE III', organization: 'S-3 OPS JEFE', role: 'S-3 JEFE', employment: 'COMANDANTE', name: 'ANDRES', lastName: 'DISDIER HEYNS', phone: '8347704', mobile: '' },
  { order: 13, unit: 'GOE III', organization: 'S-3 OPS CURSO', role: 'S-3', employment: 'SUB. TTE', name: 'CARLOS', lastName: 'GALLEGO PICO', phone: '8347928', mobile: '' },
  { order: 14, unit: 'GOE III', organization: 'S-3 OPS CURSO', role: 'S-3', employment: 'BRIGADA', name: 'BORJA', lastName: 'GUTIERREZ MERINO', phone: '8347928', mobile: '' },
  { order: 15, unit: 'GOE III', organization: 'S-3 OPS CURSO', role: 'S-3', employment: '', name: '', lastName: '', phone: '8347706', mobile: '' },
  { order: 16, unit: 'GOE III', organization: 'S-3 OPS CURSO', role: 'S-3', employment: 'CABO 1º', name: 'JESUS', lastName: 'GIL CASTRO', phone: '8347706', mobile: '' },
  { order: 17, unit: 'GOE III', organization: 'JEFE DE SOSTENIMINETO', role: 'S-4', employment: 'COMANDANTE', name: 'JAVIER', lastName: 'WAGENER CUENCA', phone: '8347709', mobile: '' },
  { order: 18, unit: 'GOE III', organization: 'JEFE S-4', role: 'S-4 JEFE', employment: 'CAPITAN', name: 'ENRIQUE NICOLAS', lastName: 'CARRATALA MENDEZ', phone: '8347545', mobile: '' },
  { order: 19, unit: 'GOE III', organization: 'JEFE SEAPO -AUX S-4', role: 'S-4', employment: '', name: '', lastName: '', phone: '8347710', mobile: '' },
  { order: 20, unit: 'GOE III', organization: '2º JEFE SEAPO', role: 'S-4', employment: 'SUB. TTE', name: 'FRANCISCO JAVIER', lastName: 'SOSA DIAZ', phone: '8347540', mobile: '' },
  { order: 21, unit: 'GOE III', organization: 'ALMACEN ABASTECIMIENTO', role: 'S-4', employment: 'CABO', name: 'JAVIER', lastName: 'SANCHEZ IRLES', phone: '8347548', mobile: '' },
  { order: 22, unit: 'GOE III', organization: 'S-4 SIGLE', role: 'S-4', employment: 'CABO 1º', name: 'GUSTAVO', lastName: 'SANCHEZ LAVAL', phone: '8347710', mobile: '' },
  { order: 23, unit: 'GOE III', organization: 'S-4 SIGLE', role: 'S-4', employment: 'CABO 1º', name: 'JOAQUIN', lastName: 'GARCIA CONSUEGRA', phone: '8347710', mobile: '' },
  { order: 24, unit: 'GOE III', organization: 'AUX COE PLM', role: 'S-4', employment: 'CABO 1º', name: 'JUAN LUIS', lastName: 'BELTRA GARCIA', phone: '8347705', mobile: '' },
  { order: 25, unit: 'GOE III', organization: 'S-4 ARMAMENTO /MUNICION', role: 'S-4', employment: 'CABO 1º', name: 'FIDEL', lastName: 'CANDELA ALTES', phone: '8347830', mobile: '' },
  { order: 26, unit: 'GOE III', organization: 'S-5 JEFE OPS FUTURAS', role: 'S-5', employment: 'COMADANTE', name: 'GONZALO', lastName: 'VIYEIRA MARTINEZ', phone: '8347698', mobile: '' },
  { order: 27, unit: 'GOE III', organization: 'S-5 OPS-FUTURAS', role: 'S-5', employment: 'CAPITAN', name: 'PEDRO', lastName: 'MARTINEZ SEVILLANO', phone: '8347582', mobile: '' },
  { order: 28, unit: 'GOE III', organization: 'S-5 PLANES', role: 'S-5', employment: 'SARGENTO 1º', name: 'MIGUEL ANGEL', lastName: 'GARCIA TERRER CERON', phone: '8347754', mobile: '' },
  { order: 29, unit: 'GOE III', organization: 'JEFE SECCION CIS', role: 'CIS', employment: 'BRIGADA', name: 'JUAN ANTONIO', lastName: 'NIETO GOMEZ', phone: '8347721', mobile: '' },
  { order: 30, unit: 'GOE III', organization: '2º JEFE SECCION CIS', role: 'CIS', employment: 'CABO MAYOR', name: 'FRANCISCO JAVIER', lastName: 'MUÑOZ PERZ', phone: '8347721', mobile: '' },
  { order: 31, unit: 'GOE III', organization: 'CIS PARQUE', role: 'CIS', employment: 'CABO 1º', name: 'DAVID', lastName: 'ESTIVAL MARTINEZ', phone: '8347719', mobile: '' },
  { order: 32, unit: 'GOE III', organization: '2º CIS PARQUE', role: 'CIS', employment: 'CABO 1º', name: 'JAVIER', lastName: 'GARCIA ALVAREZ', phone: '8347719', mobile: '' },
  { order: 33, unit: 'GOE III', organization: 'CIS CECOM/E-3', role: 'CIS', employment: 'CABO', name: 'LUIS', lastName: 'SALINAS GARCIA', phone: '8347718', mobile: '' },
  { order: 34, unit: 'GOE III', organization: 'CIS CISPOC/E-3', role: 'CIS', employment: 'CABO', name: 'DAVID', lastName: 'VENCE GONZALEZ', phone: '8347721', mobile: '' },
  { order: 35, unit: 'GOE III', organization: 'JEFE DE HABILITACION', role: 'HABILITACION', employment: 'BRIGADA', name: 'FERMIN', lastName: 'LOBATO GILLEN', phone: '8347722', mobile: '' },
  { order: 36, unit: 'GOE III', organization: 'SIGUEAL', role: 'HABILITACION', employment: 'CABO MAYOR', name: 'CARLOS', lastName: 'CARDELLER MONTERO', phone: '8347722', mobile: '' },
  { order: 37, unit: 'GOE III', organization: 'SERVICIOS SANITARIOS', role: 'SANIDAD', employment: 'TENIENTE', name: 'LORENA', lastName: 'CATALAN GUARCH,', phone: '8347712', mobile: '' },
  { order: 38, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'EO31', employment: 'CAPITAN', name: 'ANDRES', lastName: 'DEL POZO MIÑON', phone: '8347711', mobile: '' },
  { order: 39, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'ECOS 31', employment: 'BRIGADA', name: 'JORGE', lastName: 'FERNANDEZ GONZALEZ', phone: '8347711', mobile: '' },
  { order: 40, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'EO 32', employment: 'CAPITAN', name: 'JAIME', lastName: 'ANERA AREVALO', phone: '8347599', mobile: '' },
  { order: 41, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'ECOS 32', employment: 'SARGENTO', name: 'DAVID', lastName: 'AYALA LOPEZ,', phone: '8347599', mobile: '' },
  { order: 42, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'EO 33', employment: 'TTE', name: 'EDUARDO ALEJANDRO', lastName: 'DE CASTRO MUÑOZ,', phone: '8347713', mobile: '' },
  { order: 43, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'ECOS 33', employment: 'BRIGADA', name: 'DANIEL', lastName: 'SUAREZ CLEMENTE', phone: '8347713', mobile: '' },
  { order: 44, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'EO 34', employment: 'CAPITAN', name: 'PABLO', lastName: 'MARTINEZ LAMAZAREZ', phone: '8347714', mobile: '' },
  { order: 45, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'ECOS 34', employment: 'SARGENTO', name: 'FERNANDO', lastName: 'ANTON GASPAR', phone: '8347714', mobile: '' },
  { order: 46, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'EO 35', employment: 'CAPITAN', name: 'FERNANDO', lastName: 'NUÑEZ SANCHEZ', phone: '8347715', mobile: '' },
  { order: 47, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'ECOS 35', employment: 'BRIGADA', name: 'JOSE MANUEL', lastName: 'OLLER GARCIA', phone: '8347715', mobile: '' },
  { order: 48, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'EO 36', employment: 'CAPITAN', name: 'JORGE', lastName: 'SANTAMARIA GALTIER', phone: '8347716', mobile: '' },
  { order: 49, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'ECOS 36', employment: 'BRIGADA', name: 'ANTONIO', lastName: 'SANCHEZ CALERO', phone: '8347716', mobile: '' },
  { order: 50, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'EOCA', employment: 'CAPITAN', name: 'RODRIGO', lastName: 'SELLES TOMAS', phone: '8347717', mobile: '' },
  { order: 51, unit: 'GOE III', organization: 'EQUIPO OPERATIVO', role: 'ECOS EOCA', employment: 'BRIGADA', name: 'JOSE MARIA', lastName: 'SASTRE BERROCAL', phone: '8347717', mobile: '' },
  { order: 52, unit: 'GOE III', organization: 'SALA DE OPERACIONES', role: 'DEPENDENCIA', employment: '', name: '', lastName: '', phone: '8347554', mobile: '' },
  { order: 53, unit: 'GOE III', organization: 'DESTACAMENTO CAPITAN COBO', role: 'JEFE DESTACAMENTO', employment: 'SUB. TTE', name: 'FRANCISCO JAVIER', lastName: 'GALAFATE TROYA', phone: '834', mobile: '958340565' },
  { order: 54, unit: 'GOE III', organization: 'DESTACAMENTO TTE. MORENO', role: 'JEFE DESTACAMENTO', employment: 'CABO MAYOR', name: 'DAVID', lastName: 'VICENTE VIVES', phone: '8347709', mobile: '' },
  { order: 55, unit: 'GOE III', organization: 'CABO 1º DE CUARTEL', role: 'DEPENDENCIA', employment: '', name: '.', lastName: '.', phone: '8347702', mobile: '629914682' },
];


const GCG_SEEDS: Omit<PhoneContact, 'id'>[] = [
  { order: 1, unit: 'GCG', organization: 'JEFE GCG', role: 'JEFE GCG MOE', employment: 'TCOL', name: 'RUBÉN', lastName: 'GUERRA GARLITO', phone: '8347651', mobile: '8417651', email: 'rguega1@et.mde.es' },
  { order: 2, unit: 'GCG', organization: 'SUB. MAYOR', role: 'SUBOFICIALIA MAYOR', employment: 'SUB. MAYOR', name: 'ENRIQUE', lastName: 'GARCIE VOZMEDIANO', phone: '8347694', mobile: '8417694' },
  { order: 3, unit: 'GCG', organization: 'JEFE PLMM GCG', role: 'JEFE SOSTENIMIENTO', employment: 'CTE', name: 'JOSE MARIA', lastName: 'FERNANDEZ VALLESPIN', phone: '8347672', mobile: '8417301' },
  { order: 4, unit: 'GCG', organization: 'JEFE PLMM GCG', role: 'JEFE NUCLEO OPERACIONES', employment: 'CTE', name: 'PABLO', lastName: 'GARCIA GAMARRA', phone: '8347665', mobile: '8417672' },
  { order: 5, unit: 'GCG', organization: 'S-1 HOJAS', role: 'S-1 HOJAS', employment: 'CABO 1º', name: 'MARIA DEL CARMEN', lastName: 'TORRES AVILA', phone: '8347789', mobile: '' },
  { order: 6, unit: 'GCG', organization: 'S-1 AUX', role: 'S-1 AUX', employment: 'BG', name: 'PEREZ LAMPKIN', lastName: 'PABLO F.', phone: '8347727', mobile: '', email: 'pperlam@et.mde.es' },
  { order: 9, unit: 'GCG', organization: 'S-2 JEFE', role: 'S2 JEFE', employment: 'BG', name: 'JOSE ALBERTO', lastName: 'GOMEZ GIL', phone: '8417728', mobile: '' },
  { order: 10, unit: 'GCG', organization: 'S-2 INTELIGENCIA', role: 'AUX. S-2', employment: 'CABO 1º', name: 'JUAN CARLOS', lastName: 'LOPEZ MARIN', phone: '8347728', mobile: '', email: 'jlopm16@et.mde.es' },
  { order: 11, unit: 'GCG', organization: 'S-3 JEFE', role: 'OPS/SIA', employment: 'CTE', name: 'PABLO', lastName: 'GARCIA GAMARRA', phone: '8347665', mobile: '' },
  { order: 12, unit: 'GCG', organization: 'S-3 JEFE', role: 'OPS/S33', employment: 'CABO 1º', name: 'ALEJANDRO', lastName: 'MARTINEZ CANALS', phone: '8347648', mobile: '' },
  { order: 13, unit: 'GCG', organization: 'S-3 JEFE', role: 'OPS/S35', employment: 'STTE', name: 'LUIS', lastName: 'DEL ESTAL TABOADA', phone: '8347725', mobile: '' },
  { order: 14, unit: 'GCG', organization: 'S-3 JEFE', role: 'OPS/S35', employment: 'SGTO 1º', name: 'DANIEL', lastName: 'BOSCH ALCARAZ', phone: '8347725', mobile: '' },
  { order: 15, unit: 'GCG', organization: 'S-4 SOST.', role: 'S-4 SOSTENIMIENTO', employment: 'BG', name: 'ROBERTO', lastName: 'CUESTA CAÑETE', phone: '8347790', mobile: '' },
  { order: 16, unit: 'GCG', organization: 'S-4 SOST.', role: 'S-4 SOSTENIMIENTO', employment: 'CABO 1º', name: 'JOSE MIGUEL', lastName: 'RODRIGUEZ GARCIA', phone: '8347655', mobile: '' },
  { order: 18, unit: 'GCG', organization: 'S-4 SOST.', role: 'S-4 AUX PRL/CIS-POC', employment: 'CABO 1º', name: 'PEDRO A.', lastName: 'FERNANDEZ REQUENA', phone: '8347697', mobile: '8417370', email: 'pferreq@et.mde.es' },
  { order: 19, unit: 'GCG', organization: 'S-4 SOST.', role: 'AUX S-4 SOSTENIMIENTO', employment: 'CABO 1º', name: 'LUIS', lastName: 'MARTINEZ RICO', phone: '8347673', mobile: '' },
  { order: 20, unit: 'GCG', organization: 'S-4 SOST.', role: 'AUX-S-4', employment: 'CABO 1º', name: 'DANIEL', lastName: 'MATEO JIMENEZ', phone: '8347655', mobile: '' },
  { order: 21, unit: 'GCG', organization: 'HABILITACION', role: 'HABILITACION', employment: 'BG', name: 'PATROCINIO', lastName: 'BERSABE MARQUEZ', phone: '8347689', mobile: '', email: '@mde.es' },
  { order: 22, unit: 'GCG', organization: 'DEPENDENCIAS', role: 'ENFERMERIA', employment: 'CAP', name: 'ISABEL MARIA', lastName: 'GALAN CÓRDOBA', phone: '8347313', mobile: '' },
  { order: 23, unit: 'GCG', organization: 'CIA GCG', role: 'JEFE CIA CG', employment: 'CAP', name: 'RAFAEL', lastName: 'SOLANO NICOLAS', phone: '8347534', mobile: '8417420' },
  { order: 24, unit: 'GCG', organization: 'CIA GCG', role: 'AUXILIAR CIA CG', employment: 'CABO 1º', name: 'JUAN', lastName: 'ARLANDIS MELIA', phone: '8347880', mobile: '' },
  { order: 25, unit: 'GCG', organization: 'UAPOCOM', role: 'JEFE U. APOYO AL COMBATE', employment: 'CTE', name: 'JORGE IVAN', lastName: 'GOMEZ RUBIO', phone: '8347877', mobile: '8414767', email: 'jgomrub@et.mde.es' },
  { order: 26, unit: 'GCG', organization: 'UAPOCOM', role: 'JEFE EO U. DE EMBARCACIONES', employment: 'STTE', name: 'CARLOS ALBERTO', lastName: 'CASQUERO MARTIN', phone: '8347871', mobile: '', email: 'ccasmar@et.mde.es' },
  { order: 27, unit: 'GCG', organization: 'UAPOCOM', role: 'JEFE EO U. RPAS', employment: 'BG', name: 'MIGUEL ANGEL', lastName: 'LLOMPART MARTINEZ', phone: '8347872', mobile: '', email: 'mllomar1@et.mde.es' },
  { order: 28, unit: 'GCG', organization: 'UAPOCOM', role: 'EQUIPO K-9', employment: 'CABO 1º', name: '', lastName: 'ARTILES', phone: '8347641', mobile: '' },
  { order: 29, unit: 'GCG', organization: 'UAPOCOM', role: 'AUXILIAR CIA', employment: 'BG', name: 'MARTINEZ GUIRAO', lastName: 'RUTH', phone: '8347876', mobile: '8417375' },
  { order: 30, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'JEFE UINT', employment: 'CAP', name: 'FRANCISO JAVIER', lastName: 'ALEU ALCAIDE', phone: '8347581', mobile: '8417377' },
  { order: 30, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'ANALISTA GEOINT', employment: 'CABO 1º', name: 'ENCARNACION', lastName: 'MARTINEZ BELCHI', phone: '8347520', mobile: '' },
  { order: 31, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'ANALISTA GEOINT', employment: 'SGTO 1º', name: 'DARIO DE LA', lastName: 'CRUZ MERCADO', phone: '8347858', mobile: '' },
  { order: 32, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'ALTAS CAPACIDADES', employment: 'STTE', name: 'JOSE ANTONIO', lastName: 'GAGO MARTINEZ', phone: '8347658', mobile: '8417383' },
  { order: 32, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'ANALISTA OSINT', employment: 'SDO,', name: 'TABATHA', lastName: 'TORRES GALLEGO', phone: '8347613', mobile: '' },
  { order: 33, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'ANALISTA UINT', employment: 'BG', name: 'ENRIQUE', lastName: 'HUGET ROJO', phone: '8347625', mobile: '8417381' },
  { order: 34, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'ANALISTA UINT', employment: 'B', name: '', lastName: '', phone: '8347605', mobile: '' },
  { order: 35, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'ANALISTA UINT', employment: 'BG', name: 'RAUL', lastName: 'PONSODA MENDEZ', phone: '8347552', mobile: '8417382' },
  { order: 36, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'ANALISTA GEOINT', employment: 'CABO 1º', name: 'FRANCISCO C.', lastName: 'OLIVA FANO', phone: '8347858', mobile: '' },
  { order: 37, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'ANALISTA UINT', employment: 'BG', name: 'SERGIO', lastName: 'DE LAS PEÑAS CANALEJAS', phone: '8347690', mobile: '' },
  { order: 38, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'ANALISTA UINT', employment: 'SGTO 1º', name: '', lastName: '', phone: '8347539', mobile: '' },
  { order: 39, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'ANALISTA OSINT', employment: 'BG', name: 'JAVIER', lastName: 'RIPOL MAS', phone: '8347687', mobile: '' },
  { order: 39, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'ANALISTA OSINT', employment: 'SGTO 1º', name: 'FERNANDO', lastName: 'MARQUEZ BUSTILLO', phone: '8347687', mobile: '', email: 'fmarbu2@mde.es' },
  { order: 40, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'SIS', employment: '', name: '', lastName: '', phone: '8347551', mobile: '' },
  { order: 41, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'SIS', employment: '', name: '', lastName: '', phone: '8347551', mobile: '' },
  { order: 42, unit: 'GCG', organization: 'U. INTELIGENCIA', role: 'AUX.', employment: 'AUX CIA', name: 'INTEL', lastName: '', phone: '8347726', mobile: '' },
  { order: 43, unit: 'GCG', organization: 'CIA INSTRUCCION', role: 'JEFE CIA. INSTRUCCION', employment: 'CAP', name: 'ALBERTO', lastName: 'CONDE MARTINEZ', phone: '8347685', mobile: '' },
  { order: 44, unit: 'GCG', organization: 'CIA INSTRUCCION', role: 'NUCLEO APOYO A LA INSTRUCCIÓN E INSTALACIONES (NAII)', employment: 'STTE', name: 'MANUEL', lastName: 'GOMEZ GONZALEZ', phone: '8347633', mobile: '' },
  { order: 45, unit: 'GCG', organization: 'CIA INSTRUCCION', role: 'JEFE UIOE', employment: 'CAP', name: 'ALVARO', lastName: 'SAIZ RODRIGUEZ', phone: '8347674', mobile: '8417674' },
  { order: 46, unit: 'GCG', organization: 'CIA INSTRUCCION', role: 'NIATOE JEFE (N. DE INSTRUCCION AVANZADO TIRADORES)', employment: 'BG', name: 'IVAN', lastName: 'GOMEZ GARCIA', phone: '8347859', mobile: '8414766' },
  { order: 47, unit: 'GCG', organization: 'CIA INSTRUCCION', role: 'NIASOE JEFE (N. DE INSTRUCCION AVANZADO SANITARIOS OE´S)', employment: 'BG', name: 'OSCAR', lastName: 'LONGARTE MIGUEL', phone: '8347536', mobile: '8417956' },
  { order: 48, unit: 'GCG', organization: 'CIA INSTRUCCION', role: 'UIOE - SECCIÓN DE APOYO', employment: 'SARGENTO', name: 'FCO. JOSÉ', lastName: 'GARCÍA LUQUE', phone: '8347691', mobile: '' },
  { order: 48, unit: 'GCG', organization: 'CIA INSTRUCCION', role: 'NICOE (movilidad)', employment: 'SGTO.', name: 'MIGUEL', lastName: 'BECERRA  MUÑOZ', phone: '8347322', mobile: '' },
  { order: 49, unit: 'GCG', organization: 'CIA INSTRUCCION', role: 'UIOE  PERSONAL /OPS', employment: '', name: '', lastName: '', phone: '8347886', mobile: '' },
  { order: 50, unit: 'GCG', organization: 'CIA INSTRUCCION', role: 'AUXILIAR DE CIA INSTRUCCION', employment: 'CABO', name: 'ANDREA', lastName: 'MEDINA MARTINEZ', phone: '8347633', mobile: '' },
  { order: 51, unit: 'GCG', organization: 'CIA INSTRUCCION', role: 'SALA OPERACIONES UIOE', employment: 'DEPENDENCIA', name: '.', lastName: 'SALA OPERACIONES', phone: '8347691', mobile: '' },
  { order: 52, unit: 'GCG', organization: 'UOE', role: 'JEFE UOE', employment: 'CTE', name: 'FRANCISCO JOSE', lastName: 'ALONSO ABAD', phone: '8347820', mobile: '8417820' },
  { order: 53, unit: 'GCG', organization: 'UOE', role: 'EO 2', employment: 'SGTO 1º', name: 'JACOBO', lastName: 'VALDES ELORTEGUI', phone: '8347865', mobile: '' },
  { order: 54, unit: 'GCG', organization: 'UOE', role: 'EO2 UOE (2º JEFE):', employment: '', name: '', lastName: '', phone: '8347865', mobile: '' },
  { order: 55, unit: 'GCG', organization: 'UOE', role: 'EO 1', employment: 'CAP', name: 'JUAN DE DIOS', lastName: 'HERMOSIN ACASUSO', phone: '8347824', mobile: '' },
  { order: 56, unit: 'GCG', organization: 'UOE', role: 'S3 UOE', employment: 'STTE', name: 'OSCAR', lastName: 'ORFILA ARNAU', phone: '8347822', mobile: '' },
  { order: 57, unit: 'GCG', organization: 'UOE', role: 'UOE', employment: '', name: '', lastName: '', phone: '8347822', mobile: '' },
  { order: 58, unit: 'GCG', organization: 'UOE', role: 'S1/S4 UOE', employment: 'STTE', name: 'OSCAR', lastName: 'ORFILA ARNAU', phone: '8347822', mobile: '' },
  { order: 59, unit: 'GCG', organization: 'UOE', role: 'S2/S3 UOE', employment: 'SGTO 1º', name: 'JORGE', lastName: 'CALDERÓN HIDALGO', phone: '8347821', mobile: '' },
  { order: 60, unit: 'GCG', organization: 'UOE', role: 'SUB. CUARTEL UOE', employment: 'DEPENDENCIA', name: 'UOE', lastName: 'SUBOFICIAL CUARTEL', phone: '8417431', mobile: '8417431' },
  { order: 62, unit: 'GCG', organization: 'SECCION DE MANTO', role: '2º ESCALON TRANSMISIONES', employment: 'BG', name: 'JUAN A.', lastName: 'CARCEL GUTIERRREZ', phone: '8347663', mobile: '' },
  { order: 64, unit: 'GCG', organization: 'DEPENDENCIAS', role: 'CABO 1º DE CUARTEL', employment: 'CABO 1º', name: '', lastName: '', phone: '8417650', mobile: '639708232' },
  { order: 65, unit: 'GCG', organization: 'DEPENDENCIAS', role: 'CUARTELERO', employment: 'DE GCG', name: 'SDO.', lastName: '', phone: '8347813', mobile: '' },
  { order: 66, unit: 'GCG', organization: 'DEPENDENCIAS', role: 'FAX GCG', employment: 'DEPENDENCIA', name: 'FAX', lastName: 'GCG', phone: '8347910', mobile: '965237910' },
  { order: 67, unit: 'GCG', organization: 'DEPENDENCIAS', role: 'ALMACEN  GCG', employment: 'CABO 1º', name: 'DARIO ANDRES', lastName: 'DAVID ARCILA', phone: '8347883', mobile: '' },
  { order: 80, unit: 'GCG', organization: 'CIA TRANS', role: 'JEFE CIATRANS', employment: 'CAP', name: 'JAVIER', lastName: 'DELGADO MARTIN', phone: '8347695', mobile: '8417695' },
  { order: 81, unit: 'GCG', organization: 'CIA TRANS PLM', role: 'CUARTO CRIPTO', employment: 'SGTO 1º', name: 'JOSE JAVIER', lastName: 'REAL PACIOS', phone: '8347532', mobile: '' },
  { order: 81, unit: 'GCG', organization: 'CIA CG CISPOC', role: 'CISPOC', employment: 'CABO 1º', name: 'PEDRO ANTONIO', lastName: 'FERNANDEZ REQUENA', phone: '8347697', mobile: '965237697' },
  { order: 81, unit: 'GCG', organization: 'CIA TRANS PLM', role: 'PARQUE CIA TRANS', employment: 'CABO 1º', name: 'RUBEN', lastName: 'ALCARAZ SABIDO', phone: '8347532', mobile: '' },
  { order: 81, unit: 'GCG', organization: 'CIA TRANS PLM', role: 'AUXILIAR CIA', employment: 'CABO 1º', name: 'JORGE', lastName: 'DIAZ GUERRA SANCHEZ', phone: '8347696', mobile: '' },
  { order: 81, unit: 'GCG', organization: 'CIA TRANS PLM', role: 'PARQUE CIA TRANS', employment: 'SGTO 1º', name: 'JOSE JAVIER', lastName: 'REAL PACIOS', phone: '8347532', mobile: '' },
  { order: 82, unit: 'GCG', organization: 'CIA TRANS', role: 'JEFE SC CTPC PRAL', employment: 'TTE', name: 'JAVIER', lastName: 'GONZALVEZ PEREZ', phone: '8347688', mobile: '8417373' },
  { order: 82, unit: 'GCG', organization: 'CIA TRANS', role: 'JEFE SC2NET', employment: 'SARGENTO', name: '', lastName: '', phone: '8347521', mobile: '' },
  { order: 82, unit: 'GCG', organization: 'CIA TRANS', role: 'SC2NET', employment: 'SARGENTO', name: '', lastName: '', phone: '8347521', mobile: '' },
  { order: 82, unit: 'GCG', organization: 'CIA TRANS', role: 'NÚCLEO APOYO INFORMÁTICO (NAI)', employment: 'SARGENTO', name: 'RUBEN', lastName: 'FERNANDEZ GARCIA', phone: '8347533', mobile: '' },
  { order: 83, unit: 'GCG', organization: 'CIA TRANS', role: 'JEFE PELOTÓN RADIO', employment: 'SARGENTO', name: 'FRANCISCO', lastName: 'BERBEL CASTELLANO', phone: '8347530', mobile: '' },
  { order: 83, unit: 'GCG', organization: 'CIA TRANS', role: 'PELOTÓN  RADIO', employment: 'SARGENTO', name: 'MARCO', lastName: 'HARRIS PEREZ', phone: '8347530', mobile: '' },
  { order: 85, unit: 'GCG', organization: 'CIA TRANS', role: 'JEFE PELOTON SATELITE', employment: 'SARGENTO', name: 'DANIEL', lastName: 'PARRA SAN MARTIN', phone: '8347530', mobile: '' },
  { order: 85, unit: 'GCG', organization: 'CIA TRANS', role: 'JEFE SC CEMA', employment: 'TTE', name: 'JAVIER', lastName: 'GONZALVEZ PEREZ', phone: '8347688', mobile: '' },
  { order: 85, unit: 'GCG', organization: 'CIA TRANS', role: 'JEFE SC CPTC FOB', employment: 'TTE', name: 'IGNACIO', lastName: 'GARCIA MEZO', phone: '8347650', mobile: '' },
  { order: 86, unit: 'GCG', organization: 'CIA TRANS', role: 'CECOM OP. CIATRANS FAX', employment: 'DEPENDENCIA', name: 'CIA TRANS', lastName: 'CECOM OP', phone: '8347869', mobile: '' },
  { order: 86, unit: 'GCG', organization: 'CIA TRANS', role: 'CECOM OP. CIA TRAS', employment: 'DEPENDENCIA', name: 'CIA TRANS', lastName: 'CECOM OP.', phone: '8347867', mobile: '' },
  { order: 86, unit: 'GCG', organization: 'CIA TRANS', role: 'CECOM OP. CIA TRANS', employment: 'DEPENDENCIA', name: 'CIA TRANS', lastName: 'CECOM OP.', phone: '8347868', mobile: '' },
  { order: 86, unit: 'GCG', organization: 'CIA TRANS', role: 'CECOM DE OPERACIONES', employment: 'DEPENDENCIA', name: '', lastName: 'CECOM OP. CIA TRANS', phone: '8347869', mobile: '' },
  { order: 87, unit: 'GCG', organization: 'S-4 SOST.', role: 'JEFE SEAPO', employment: 'SGTO 1º', name: 'OSCAR', lastName: 'GALAN PORTILLO', phone: '8347597', mobile: '' },
];


const CG_MANDO_SEEDS: Omit<PhoneContact, 'id'>[] = [
  { order: 1, unit: 'CG MANDO', organization: 'GEMOE', role: 'GENERAL JEFE MOE', employment: 'GENERAL DE BG', name: 'MIGUEL ANGEL', lastName: 'JIMENEZ PAREJO', phone: '8347600', mobile: '8417600', email: 'mjimpar@et.mde.es' },
  { order: 2, unit: 'CG MANDO', organization: 'CORONEL 2º JEFE', role: '2º JEFE', employment: 'CORONEL', name: 'JOSE IGNACIO', lastName: 'VALVERDE MORENO', phone: '8347700', mobile: '8417700', email: 'jvalvere@et.mde.es' },
  { order: 3, unit: 'CG MANDO', organization: 'SUBOFICIAL MAYOR', role: 'SUBOFICIAL MAYOR', employment: 'SUB. MAYOR', name: 'FRANCISCO DE ASIS', lastName: 'VAZQUEZ CORTEJOSO', phone: '8347639', mobile: '8417639', email: 'fvazcor@et.mde.es' },
  { order: 10, unit: 'CG MANDO', organization: 'SECRETARIA GEMOE', role: 'JEFE OFICINA COMUNICACIÓN PÚBLICA', employment: 'TCOL', name: 'ALFREDO', lastName: 'BERNABEU MONTILLA', phone: '8347320', mobile: '8417623', email: 'abermon@et.mde.es' },
  { order: 11, unit: 'CG MANDO', organization: 'SECRETARIA GEMOE', role: 'SECRETARIA GEMOE', employment: 'STTE', name: 'JOSE MANUEL', lastName: 'ZARAGOZA SANCHIS', phone: '8347637', mobile: '8417645', email: 'jzarsa1@et.mde.es' },
  { order: 12, unit: 'CG MANDO', organization: 'SECRETARIA GEMOE', role: 'AUXILIAR OFICINA COMUNICACION', employment: 'CBMY', name: 'NOELIA', lastName: 'BURCIO DIAZ', phone: '8347604', mobile: '8417638', email: 'nburdia@et.mde.es' },
  { order: 13, unit: 'CG MANDO', organization: 'SECRETARIA GEMOE', role: 'SECRETARIA GEMOE AUXILIAR', employment: 'CABO', name: 'ALEXANDRA', lastName: 'GUERRERO ANTON', phone: '8347638', mobile: '8417335', email: 'agueant@et.mde.es' },
  { order: 14, unit: 'CG MANDO', organization: 'SECRETARIA GEMOE', role: 'SECRETARIA GEMOE AUXILIAR', employment: 'SOLDADO', name: 'ANA BELEN', lastName: 'ALARCÓN AVILES', phone: '8347645', mobile: '8417336', email: 'aalaavi@mde.es' },
  { order: 15, unit: 'CG MANDO', organization: 'CG CONDUCTORES', role: 'CONDUCTORES', employment: '', name: '', lastName: '', phone: '8347636', mobile: '' },
  { order: 20, unit: 'CG MANDO', organization: 'CG SAE', role: 'JEFE SECCION ASUNTOS ECONOMICOS', employment: 'CTE', name: 'FRANCISCO JAVIER', lastName: 'LOPEZ RUIZ', phone: '8347730', mobile: '8417730', email: 'flopezr@et.mde.es' },
  { order: 22, unit: 'CG MANDO', organization: 'CG SAE', role: 'DIETAS', employment: 'CAP', name: 'GONZALO', lastName: 'HUERTA CABALLERO', phone: '8347733', mobile: '8417733' },
  { order: 23, unit: 'CG MANDO', organization: 'CG SAE', role: 'LIQUIDACIONES', employment: 'TTE', name: 'PEDRO', lastName: 'CHAO MENÉNDEZ', phone: '8347737', mobile: '8417737' },
  { order: 24, unit: 'CG MANDO', organization: 'CG SAE', role: 'CONTRATACION', employment: 'TTE', name: 'JUAN', lastName: 'MEDINA MUNUERA', phone: '8347735', mobile: '8417735', email: 'jmedmu2@mde.es' },
  { order: 25, unit: 'CG MANDO', organization: 'CG SAE', role: 'ADMINISTRACION', employment: 'STTE', name: 'GUSTAVO', lastName: 'RODRIGUEZ OLMEDO', phone: '8347918', mobile: '8417360', email: 'grodolm@et.mde.es' },
  { order: 26, unit: 'CG MANDO', organization: 'CG SAE', role: 'HABILITACIÓN CG AUXILIAR', employment: 'SOLDADO', name: 'OSCAR', lastName: 'ABRALDES RODRIGUEZ', phone: '8347603', mobile: '8417304', email: 'oabrrod@mde.es' },
  { order: 27, unit: 'CG MANDO', organization: 'CG SAE', role: 'SECRETARÍA SAE', employment: 'CABO 1º', name: 'JONATHAN', lastName: 'FERRIS GUERRERO', phone: '8347732', mobile: '8417732', email: 'yfergue@et.mde.es' },
  { order: 29, unit: 'CG MANDO', organization: 'CG SAE', role: 'SAE', employment: '', name: '', lastName: '', phone: '8347729', mobile: '' },
  { order: 30, unit: 'CG MANDO', organization: 'AUDIOVISUALES', role: 'AUDIOVISUALES', employment: 'CABO 1º', name: 'MIGUEL ANGEL', lastName: 'SANCHEZ ESCRIBANO', phone: '8347656', mobile: '', email: 'msanesc@mde.es' },
  { order: 31, unit: 'CG MANDO', organization: 'AUDIOVISUALES', role: 'AUDIOVISUALES', employment: 'SOLDADO', name: 'ADRIAN', lastName: 'PEREZ GARCIA', phone: '8347656', mobile: '8417299', email: 'aperg39@et.mde.es' },
  { order: 40, unit: 'CG MANDO', organization: 'SERVICIO RELIGIOSO', role: 'PATER', employment: 'TCOL', name: 'FRANCISCO JOSE', lastName: 'SIERRA VILCHEZ', phone: '8347799', mobile: '8407799', email: 'fsievil@et.mde.es' },
  { order: 50, unit: 'CG MANDO', organization: 'DEPENDENCIAS', role: 'SIERRA NEVADA', employment: 'STTE', name: 'FRANCISCO JAVIER', lastName: 'GALAFATE TROYA', phone: '8417714', mobile: '', email: 'fgaltro@et.mde.es' },
  { order: 51, unit: 'CG MANDO', organization: 'DEPENDENCIAS', role: 'CABO ROIG', employment: 'CABO 1º', name: '', lastName: '', phone: '', mobile: '8417709' },
  { order: 90, unit: 'CG MANDO', organization: 'DEPENDENCIAS', role: 'VESTUARIO GENERAL', employment: 'DEPENDENCIA', name: 'GENERAL', lastName: 'VESTUARIO', phone: '8347680', mobile: '' },
  { order: 91, unit: 'CG MANDO', organization: 'DEPENDENCIAS', role: 'ZONA ACCESO MANDO 1ª PLANTA', employment: 'DEPENDENCIA', name: 'PLANTA', lastName: 'PRIMERA', phone: '8347659', mobile: '' },
  { order: 92, unit: 'CG MANDO', organization: 'DEPENDENCIAS', role: 'ZONA ACCESO MANDO SÓTANO', employment: 'DEPENDENCIA', name: 'SÓTANO', lastName: 'MANDO', phone: '8347658', mobile: '' },
  { order: 93, unit: 'CG MANDO', organization: 'DEPENDENCIAS', role: 'VETERANOS BOINAS VERDES', employment: 'DEPENDENCIA', name: 'BOINAS VERDES', lastName: 'VETERANOS', phone: '8347746', mobile: '' },
];


const CG_ESTADO_MAYOR_SEEDS: Omit<PhoneContact, 'id'>[] = [
  { order: 1, unit: 'CG ESTADO MAYOR', organization: 'JEFE ESTADO MAYOR', role: 'JEFE ESTADO MAYOR', employment: 'TCOL', name: 'ALVARO', lastName: 'DE HITA GARCÍA', phone: '8347601', mobile: '8417601', email: 'adehga1@et.mde.es' },
  { order: 2, unit: 'CG ESTADO MAYOR', organization: 'SECRETARIA JEM', role: 'SECRETARIO DEL TCOL. JEM', employment: 'CABO', name: 'JUAN FRANCISCO', lastName: 'VILLANUEVA CÓRDOBA', phone: '8347602', mobile: '8407602', email: 'jvilcor@et.mde.es' },
  { order: 3, unit: 'CG ESTADO MAYOR', organization: 'SECRETARIA JEM', role: 'SALA DE REUNIONES Y VTC', employment: 'DEPENDENCIA', name: 'ESTADO MAYOR', lastName: 'SALA DE REUNIONES Y VTC', phone: '8347635', mobile: '' },
  { order: 4, unit: 'CG ESTADO MAYOR', organization: 'EM DEPENDENCIAS', role: 'CTE SERVICIO EM', employment: 'CTE', name: '.', lastName: 'CTE DE SERVICIO EM', phone: '8417604', mobile: '629910046' },
  { order: 10, unit: 'CG ESTADO MAYOR', organization: 'EM JEFE G-1', role: 'G-1 JEFE', employment: 'CTE', name: 'AURELIO', lastName: 'ORTEGA MADROÑAL', phone: '8347644', mobile: '8417644', email: 'aortmad@mde.es' },
  { order: 11, unit: 'CG ESTADO MAYOR', organization: 'EM G-1', role: 'G-1 JEFE PLANES Y OPERACIONES', employment: 'CTE', name: 'ISIDORO', lastName: 'TORRES MARMOL', phone: '8347800', mobile: '8417305', email: 'itormar@et.mde.es' },
  { order: 12, unit: 'CG ESTADO MAYOR', organization: 'EM G-1', role: 'G-1 OPERACIONES', employment: 'BG', name: 'FRANCISCO ENRIQUE', lastName: 'LORENTE CARCELES', phone: '8347607', mobile: '8417607', email: 'florcar@et.mde.es' },
  { order: 13, unit: 'CG ESTADO MAYOR', organization: 'EM G-1', role: 'G-1 PLANES', employment: 'CABO 1º', name: 'FROILAN', lastName: 'PITA LOPEZ', phone: '8347331', mobile: '', email: 'fpitlop@mde.es' },
  { order: 13.1, unit: 'CG ESTADO MAYOR', organization: 'EM G-1', role: 'G-1 PLANES', employment: 'CABO 1º', name: 'ARANZAZU', lastName: 'CORDÓN GARCÍA', phone: '8347331', mobile: '', email: 'acorga3@mde.es' },
  { order: 14, unit: 'CG ESTADO MAYOR', organization: 'EM G-1', role: 'G-1 JUSTICIA', employment: 'CAP', name: 'ROBERTO JOSE', lastName: 'GARCIA ORTEGA', phone: '8347653', mobile: '8417653', email: 'rgarort2@et.mde.es' },
  { order: 15, unit: 'CG ESTADO MAYOR', organization: 'EM G-1', role: 'G-1 JEFE DE GESTION', employment: 'BG', name: 'SALVADOR', lastName: 'CAMPUZANO PEÑARANDA', phone: '8347654', mobile: '8417654', email: 'scampen@et.mde.es' },
  { order: 16, unit: 'CG ESTADO MAYOR', organization: 'EM G-1', role: 'G-1 AUXILIAR DE PERSONAL', employment: 'CABO MAYOR', name: 'JESÚS', lastName: 'RAMIREZ REVERTE', phone: '8347675', mobile: '', email: 'jramrev@et.mde.es' },
  { order: 17, unit: 'CG ESTADO MAYOR', organization: 'EM G-1', role: 'G-1 JEFE HOJAS / IPEC', employment: '', name: '', lastName: '', phone: '8347652', mobile: '8417652' },
  { order: 18, unit: 'CG ESTADO MAYOR', organization: 'EM G-1', role: 'G-1 HOJAS / IPEC', employment: 'CABO MAYOR', name: 'CRISTIAN', lastName: 'GARCIA GUARDIOLA', phone: '8347608', mobile: '8417608', email: 'cgargua@interno.mde.es' },
  { order: 19, unit: 'CG ESTADO MAYOR', organization: 'EM G-1', role: 'G-1 APOYOS SANITARIOS', employment: 'CABO', name: 'MIRIAM', lastName: 'DURA PINTEÑO', phone: '8347676', mobile: '8417306', email: 'mdurpin@mde.es' },
  { order: 20, unit: 'CG ESTADO MAYOR', organization: 'EM JEFE G-2', role: 'G-2 JEFE', employment: 'CTE', name: 'JOSE RAUL', lastName: 'SANCHEZ DELGADO', phone: '8347614', mobile: '8417614', email: 'jsand20@et.mde.es' },
  { order: 21, unit: 'CG ESTADO MAYOR', organization: 'EM G-2', role: 'G-2 SEGURIDAD / INTEL', employment: 'CTE', name: 'IVAN', lastName: 'SANCHO GUTIERREZ', phone: '8347620', mobile: '8417365', email: 'isangut@mde.es' },
  { order: 22, unit: 'CG ESTADO MAYOR', organization: 'EM G-2', role: 'G-2 CONTRAINT / SEG', employment: 'STTE', name: 'JOSE', lastName: ' LOPEZ BARCELO', phone: '8347616', mobile: '8417344', email: 'jlopba3@et.mde.es' },
  { order: 24, unit: 'CG ESTADO MAYOR', organization: 'EM G-2', role: 'G-2 PCO111', employment: 'BG', name: 'ANDRES JESUS', lastName: 'MOLINA MORALES', phone: '8347686', mobile: '8417347', email: 'amolmor@et.mde.es' },
  { order: 25, unit: 'CG ESTADO MAYOR', organization: 'EM G-2', role: 'G-2 JEFE SLPMC', employment: 'BG', name: 'ADRIAN', lastName: 'DEL AMO LOPEZ', phone: '8347624', mobile: '8417346', email: 'aamolo2@et.mde.es' },
  { order: 26, unit: 'CG ESTADO MAYOR', organization: 'EM G-2', role: 'G-2 AUXILIAR SLPMC', employment: 'SOLDADO', name: 'MARIA JOSE', lastName: 'PASTOR BROTONS', phone: '8347617', mobile: '8417348', email: 'mpasbro@mde.es' },
  { order: 30, unit: 'CG ESTADO MAYOR', organization: 'EM JEFE G-3', role: 'G-3 JEFE', employment: 'CTE', name: 'ENRIQUE VICENTE', lastName: 'JIMENEZ GARRIGA', phone: '8347618', mobile: '8417618', email: 'amarca4@et.mde.es' },
  { order: 31, unit: 'CG ESTADO MAYOR', organization: 'EM G-3', role: 'G-3 JEFE OPERACIONES', employment: 'CTE', name: 'FRANCISCO JOSE', lastName: 'GONZALEZ ORTÍN', phone: '8347683', mobile: '8417307', email: 'fgonor1@mde.es' },
  { order: 32, unit: 'CG ESTADO MAYOR', organization: 'EM G-3', role: 'G-3 OPERACIONES', employment: 'BG', name: 'RAMSÉS', lastName: 'SAMPER SANZ', phone: '8347619', mobile: '8417364', email: 'rsamsan@mde.es' },
  { order: 33, unit: 'CG ESTADO MAYOR', organization: 'EM G-3', role: 'G-3 CREDITOS', employment: 'BG', name: 'JAVIER VICENTE', lastName: 'GARCIA CARBONELL', phone: '8347684', mobile: '', email: 'jgarc11@et.mde.es' },
  { order: 34, unit: 'CG ESTADO MAYOR', organization: 'EM G-3', role: 'G-3 JEFE SIA', employment: 'CAP', name: 'CARLOS', lastName: 'MEZIAT VALVERDE', phone: '8347606', mobile: '8417352', email: 'cmezval@et.mde.es' },
  { order: 35, unit: 'CG ESTADO MAYOR', organization: 'EM G-3', role: 'G-3 SIA', employment: 'STTE', name: 'FRANCISCO RAMON', lastName: 'MORENO NAVARRO', phone: '8347621', mobile: '8417349', email: 'fmornav@et.mde.es' },
  { order: 36, unit: 'CG ESTADO MAYOR', organization: 'EM G-3', role: 'G-3 AUXILIAR SIA', employment: 'CABO 1º', name: 'BEATRIZ', lastName: 'SANJUAN PÉREZ', phone: '8347610', mobile: '', email: 'slopcee@et.mde.es' },
  { order: 37, unit: 'CG ESTADO MAYOR', organization: 'EM G-3', role: 'G-3 AUXILIAR SIA', employment: 'CABO 1º', name: 'ROSA ANA', lastName: 'LLUCH GARRIGOS', phone: '8347692', mobile: '8417350', email: 'rllugar@et.mde.es' },
  { order: 38, unit: 'CG ESTADO MAYOR', organization: 'EM G-3', role: 'G-3 AIRE', employment: 'BG', name: 'CARLOS', lastName: 'TOMAS GIL', phone: '8347528', mobile: '8414778', email: 'ctomgil@et.mde.es' },
  { order: 39, unit: 'CG ESTADO MAYOR', organization: 'EM G-3', role: 'G-3 OPERACIONES BILATERALES', employment: 'CTE', name: 'ALBERTO', lastName: 'RUIZ BIELSA', phone: '8347348', mobile: '8417358', email: 'aruibie@mde.es' },
  { order: 40, unit: 'CG ESTADO MAYOR', organization: 'EM JEFE G-4', role: 'G-4 JEFE', employment: 'CTE', name: 'ANTONIO', lastName: 'PÉREZ MAYOR', phone: '8347609', mobile: '8417609', email: 'apermay@et.mde.es' },
  { order: 41, unit: 'CG ESTADO MAYOR', organization: 'EM G-4', role: 'G-4 JEFE OPERACIONES', employment: 'STTE', name: 'ROBERTO', lastName: 'GRAN SANCHIS', phone: '8347740', mobile: '8417308', email: 'rgrasan@mde.es' },
  { order: 42, unit: 'CG ESTADO MAYOR', organization: 'EM G-4', role: 'G-4 OPERACIONES', employment: 'CABO 1º', name: 'JOSE FRANCISCO', lastName: 'GONZÁLEZ RODRÍGUEZ', phone: '8437647', mobile: '', email: 'jgonro1@et.mde.es' },
  { order: 43, unit: 'CG ESTADO MAYOR', organization: 'EM G-4', role: 'G-4 JEFE PLANES', employment: 'CTE', name: 'ANGEL', lastName: 'IBARRA MOLLA', phone: '8347657', mobile: '8414743', email: 'aibamol@et.mde.es' },
  { order: 44, unit: 'CG ESTADO MAYOR', organization: 'EM G-4', role: 'G-4 PLANES', employment: 'BG', name: 'MARCOS', lastName: 'DIAZ VIDAL', phone: '8347667', mobile: '', email: 'mdiavid@et.mde.es' },
  { order: 45, unit: 'CG ESTADO MAYOR', organization: 'EM G-4', role: 'G-4 JEFE GESTION Y RECURSOS', employment: 'BG', name: 'JORDI', lastName: 'GARCÍA GOMEZ', phone: '8347611', mobile: '8414749', email: 'jgar180@et.mde.es' },
  { order: 46, unit: 'CG ESTADO MAYOR', organization: 'EM G-4', role: 'G-4 GESTION Y RECURSOS', employment: '', name: '', lastName: '', phone: '8347649', mobile: '8417951' },
  { order: 49, unit: 'CG ESTADO MAYOR', organization: 'EM G-4', role: 'G-4 GESTION Y RECURSOS', employment: 'DEPENDENCIA', name: '', lastName: 'SALA SISTEMAS LOG', phone: '8347678', mobile: '' },
  { order: 50, unit: 'CG ESTADO MAYOR', organization: 'EM JEFE G-5', role: 'G-5 JEFE', employment: 'CTE', name: 'VALENTIN', lastName: 'ALARCÓN ALBERT', phone: '8347623', mobile: '8417987', email: 'valaalb@et.mde.es' },
  { order: 51, unit: 'CG ESTADO MAYOR', organization: 'EM G-5', role: 'G-5 PLANES', employment: 'CTE', name: 'JOSE CARLOS', lastName: 'LEZCANO MEDINA', phone: '8347630', mobile: '8417354', email: 'jlezmed@et.mde.es' },
  { order: 52, unit: 'CG ESTADO MAYOR', organization: 'EM G-5', role: 'G-5 PLANES', employment: 'BG', name: 'ALEJANDRO', lastName: 'GARCIA GARCIA', phone: '8347629', mobile: '8417629', email: 'agarg22@et.mde.es' },
  { order: 53, unit: 'CG ESTADO MAYOR', organization: 'EM G-5', role: 'G-5 SALA CLASE 1ª', employment: '', name: '', lastName: '', phone: '8347622', mobile: '' },
  { order: 60, unit: 'CG ESTADO MAYOR', organization: 'EM JEFE G-6', role: 'G-6 JEFE', employment: 'CTE', name: 'FRANCISCO JAVIER', lastName: 'BRIONES RICO', phone: '8347627', mobile: '8417627', email: 'jbriones@et.mde.es' },
  { order: 61, unit: 'CG ESTADO MAYOR', organization: 'EM G-6', role: 'G-6 COMUNICACIONES', employment: 'CAP', name: 'JESUS JAVIER', lastName: 'NICOLAS GOMARIZ', phone: '8347670', mobile: '8417459', email: 'jnicgom@et.mde.es' },
  { order: 63, unit: 'CG ESTADO MAYOR', organization: 'EM G-6', role: 'G-6 SIST. INFO. / INFOSEC', employment: 'BG', name: 'JUAN CARLOS', lastName: 'OÑATE CAMINS', phone: '8347643', mobile: '8417643', email: 'jonacam@et.mde.es' },
  { order: 64, unit: 'CG ESTADO MAYOR', organization: 'EM G-6', role: 'G-6 AUXILIAR / CRYPTO', employment: 'SGTO 1º', name: 'JESUS', lastName: 'HERNANDEZ GARCIA', phone: '8347527', mobile: '8417300', email: 'jherg26@et.mde.es' },
  { order: 65, unit: 'CG ESTADO MAYOR', organization: 'EM G-6', role: 'G-6 AUXILIAR', employment: 'CABO1º', name: 'MIGUEL ÁNGEL', lastName: 'BORGOÑOZ NIEVES', phone: '8347818', mobile: '', email: 'mbornie@et.mde.es' },
  { order: 66, unit: 'CG ESTADO MAYOR', organization: 'EM G-6 CIS', role: 'G-6 JEFE INFORMATICA (CIS)', employment: 'BG', name: 'SALVADOR', lastName: 'OTON SAURA', phone: '8347626', mobile: '8417628', email: 'sotosau@et.mde.es' },
  { order: 67, unit: 'CG ESTADO MAYOR', organization: 'EM G-6', role: 'G-6 2º JEFE INFORMATICA (CIS)', employment: 'BG', name: 'DANIEL', lastName: 'MATEU TALAVERA', phone: '8347628', mobile: '8417312', email: 'dmattal@et.mde.es' },
  { order: 68, unit: 'CG ESTADO MAYOR', organization: 'EM G-6 CIS', role: 'G-6 INFORMATICA (CIS)', employment: 'CABO 1º', name: 'JOAQUIN', lastName: 'CANTOS ARAQUE', phone: '8347626', mobile: '', email: 'jcanara@et.mde.es' },
  { order: 69, unit: 'CG ESTADO MAYOR', organization: 'EM G-6 CIS', role: 'G-6 INFORMATICA (CIS)', employment: 'SOLDADO', name: 'RAMÓN', lastName: 'GUILABERT CARTAGENA', phone: '8347628', mobile: '' },
  { order: 70, unit: 'CG ESTADO MAYOR', organization: 'EM JEFE G-7', role: 'G-7 JEFE', employment: 'CTE', name: 'MANUEL ARCADIO', lastName: 'GARCIA DE LEON LORENZO', phone: '8347632', mobile: '8417632', email: 'mgarlor@et.mde.es' },
  { order: 71, unit: 'CG ESTADO MAYOR', organization: 'EM G-7', role: 'G-7 AUXILIAR', employment: 'BG', name: 'MIGUEL ANGEL', lastName: 'MONTESINOS BUTRON', phone: '8347537', mobile: '8417537', email: 'mmonbut@mde.es' },
  { order: 72, unit: 'CG ESTADO MAYOR', organization: 'EM G-7', role: 'G-7 EJERCICIOS', employment: 'CAP', name: 'IGNACIO', lastName: 'LIÑAN DELAGE', phone: '8347537', mobile: '8417357', email: 'jreciba@mde.es' },
  { order: 73, unit: 'CG ESTADO MAYOR', organization: 'EM G-7', role: 'G-7 PROCEDIMIENTOS', employment: '', name: '', lastName: '', phone: '8347537', mobile: '8417356' },
  { order: 74, unit: 'CG ESTADO MAYOR', organization: 'EM G-7', role: 'G-7 ESPECIALIDADES', employment: 'CABO 1º', name: 'SALVADOR', lastName: 'BUYOLO SOLER', phone: '8347632', mobile: '', email: 'sbuysol@et.mde.es' },
];


const CECOM_1307_SEEDS: Omit<PhoneContact, 'id'>[] = [
  { order: 1, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: 'JEFE CECOM', employment: 'CAP', name: 'PABLO', lastName: 'VAZQUEZ PAREDES', phone: '8347503', mobile: '8417503', email: 'pvazpar@mde.es' },
  { order: 2, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: '2º JEFE CECOM', employment: 'BG', name: 'MIGUEL ANGEL', lastName: 'RIVERA GARNICA', phone: '8347519', mobile: '', email: 'mrivgar@et.mde.es' },
  { order: 3, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: 'JEFE EXPLOTACIÓN', employment: 'BG', name: 'DAVID', lastName: 'MARTINEZ LÓPEZ', phone: '8347506', mobile: '', email: 'dmarlo5@et.mde.es' },
  { order: 4, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: 'JEFE ÁREA INFORMÁTICA', employment: 'SGTO 1º', name: 'FRANCISCO ANTONIO', lastName: 'LOPEZ VICEDO', phone: '8347526', mobile: '', email: 'flopvic@et.mde.es' },
  { order: 5, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: '2º JEFE ÁREA INFORMÁTICA', employment: 'SARGENTO', name: 'FRANCISCO JAVIER', lastName: 'MONTERO MONTERO', phone: '8347508', mobile: '', email: 'fmonmo2@mde.es' },
  { order: 6, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: 'EQUIPO INFORMÁTICA', employment: 'CABO', name: 'MACARENA', lastName: 'PEREZ MARTÍN', phone: '8347516', mobile: '', email: 'mperma3@et.mde.es' },
  { order: 7, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: 'EQUIPO INFORMÁTICA', employment: 'CABO', name: 'HECTOR', lastName: 'VIZOSO ABAD', phone: '', mobile: '' },
  { order: 8, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: 'OFICINA PLM CECOM', employment: 'CABO 1º', name: 'RAQUEL', lastName: 'BENET MARTINEZ', phone: '8347505', mobile: '', email: 'rbenma1@et.mde.es' },
  { order: 9, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: 'JEFE EQUIPO LINEAS', employment: 'SGTO1º', name: 'MANUEL', lastName: 'TARANCÓN PASCUAL', phone: '8347507', mobile: '', email: 'mtarpas@mde.es' },
  { order: 10, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: 'SALA EQUIPOS', employment: 'DEPENDENCIA', name: '', lastName: 'SALA EQUIPOS', phone: '8347518', mobile: '' },
  { order: 11, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: 'FAX', employment: 'DEPENDENCIA', name: '', lastName: 'FAX', phone: '8347513', mobile: '' },
  { order: 12, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: 'OP. CIFRA', employment: 'DEPENDENCIA', name: '', lastName: 'OP. CIFRA', phone: '8347511', mobile: '' },
  { order: 13, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: '----------', employment: '----------', name: '----------', lastName: 'HALL ACCESO CECOM', phone: '8347509', mobile: '' },
  { order: 14, unit: 'CECOM 1307', organization: 'CECOM TFNO. DE SERVICIO', role: 'SUBOFICIAL DE SERVICIO CIS', employment: '----------', name: '----------', lastName: '----------', phone: '', mobile: '8417517' },
  { order: 15, unit: 'CECOM 1307', organization: 'CECOM DEPENDENCIAS', role: 'OPERADOR DE SERVICIO CIS', employment: '----------', name: '----------', lastName: '----------', phone: '', mobile: '8402149' },
  { order: 16, unit: 'CECOM 1307', organization: 'CECOM ALFÉREZ ROJAS (T-1307)', role: 'CENTRAL', employment: 'OP. DE SERVICIO', name: 'CENTRAL', lastName: '', phone: '8347500', mobile: '' },
];


export const PHONE_SEEDS: Omit<PhoneContact, 'id'>[] = [
  ...BOEL_XIX_SEEDS,
  ...USAC_SEEDS,
  ...ULOE_SEEDS,
  ...SVC_SANITARIO_SEEDS,
  ...GOE_IV_SEEDS,
  ...GOE_III_SEEDS,
  ...GCG_SEEDS,
  ...CG_MANDO_SEEDS,
  ...CG_ESTADO_MAYOR_SEEDS,
  ...CECOM_1307_SEEDS,
];
