
import { RTIWork, RTIReport } from '../types';
import { ALL_BUILDINGS } from './buildingsData';

const getBN = (id: string) => ALL_BUILDINGS.find(b => b.id === id)?.name || id;

export const RTI_REPORT_SEED: RTIReport = {
  id: 'rti_report_2025',
  inspectionDate: '2025-09-30',
  nextInspectionDate: '2027-09-30',
  summary: 'Revista Técnica de la Infraestructura realizada en septiembre de 2025. Se identificaron múltiples necesidades de inversión en mantenimiento mayor y adecuación de espacios, especialmente en lo referente a cubiertas de fibrocemento, instalaciones eléctricas y sistemas de seguridad.',
  status: 'vigente'
};

export const RTI_WORKS_SEED: RTIWork[] = [
  // ACUARTELAMIENTO PRINCIPAL
  {
    id: 'rti-work-1',
    buildingId: 'CT_1_2',
    buildingName: getBN('CT_1_2'),
    location: 'Centros Transformación 1 y 2',
    description: 'Reparación celdas eléctricas (averías, disparos frecuentes)',
    proposedYears: ['2025'],
    estimatedCost: 180000,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Personas / Operatividad',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-2',
    buildingId: 'I0021',
    buildingName: 'Instalación petrolífera',
    location: 'Instalación petrolífera',
    description: 'Nuevo depósito gasolina + surtidor para híbridos y embarcaciones',
    proposedYears: ['2024', '2025'],
    estimatedCost: 270000,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Operatividad',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-3',
    buildingId: 'E0065',
    buildingName: getBN('E0065'),
    location: 'Edificio 65 (ala derecha)',
    description: 'Adecuación para oficinas G1 y G4 (cripto, jefes, baño común)',
    proposedYears: ['2024', '2025'],
    estimatedCost: 120000,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Operatividad',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-4',
    location: 'Varias zonas',
    description: 'Instalación de 6 pararrayos (fuera de cobertura actual)',
    proposedYears: ['2023', '2025'],
    estimatedCost: 170000,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Personas (normativa PRL)',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-5',
    buildingId: 'E023',
    buildingName: getBN('E023'),
    location: 'Edificio 023 (cocina comedor)',
    description: 'Adaptación PCI: extinción automática, BIES, detectores, central, pulsadores',
    proposedYears: ['2023', '2025'],
    estimatedCost: 80000,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Personas (incendios)',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-6',
    location: 'Aparcamientos',
    description: 'Instalación 3 cargadores dobles 22 kW (132 kW total)',
    proposedYears: ['2024', '2025'],
    estimatedCost: 43000,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Movilidad sostenible',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-7',
    location: 'Viales varios',
    description: 'Reparación asfaltado (baches, fresado, capa rodadura, señalización)',
    proposedYears: ['2019', '2021', '2023', '2025'],
    estimatedCost: 413755,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Personas / Operatividad',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-8',
    buildingId: 'E0017',
    buildingName: getBN('E0017'),
    location: 'Edificio 17 (JOC, CIS)',
    description: 'Sustitución cubierta fibrocemento (935 m2) + reparación cerramiento',
    proposedYears: ['2023', '2025'],
    estimatedCost: 200000,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Operatividad / Personas (amianto/humedades)',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-9',
    buildingId: 'E0035',
    buildingName: getBN('E0035'),
    location: 'Edificio 35',
    description: 'Adecuación antiguo almacén y oficinas (Inhabilitado por amianto)',
    proposedYears: ['2023', '2025'],
    estimatedCost: 260000,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Personas (amianto)',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-10',
    buildingId: 'E0010',
    buildingName: getBN('E0010'),
    location: 'Edificio 10',
    description: 'Reforma integral aseos y vestuarios GOE III y GCG (humedades, charcos, temperatura insalubre)',
    proposedYears: ['2021', '2023'],
    estimatedCost: 250000,
    priority: 'No en 2025',
    priorityStatus: 'No en 2025',
    risk: 'Personas / Operatividad',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-11',
    buildingId: 'E0059',
    buildingName: getBN('E0059'),
    location: 'Edificio 59',
    description: 'Adecuación vestuarios GOE IV (cubierta y estructura madera en mal estado)',
    proposedYears: ['2023'],
    estimatedCost: 150000,
    priority: 'No en 2025',
    priorityStatus: 'No en 2025',
    risk: 'Personas',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-12',
    buildingId: 'E0047',
    buildingName: getBN('E0047'),
    location: 'Edificio 47',
    description: 'Acondicionamiento almacén (inhabilitado por desprendimientos)',
    proposedYears: ['2023', '2025'],
    estimatedCost: 98991,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Operatividad',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-13',
    buildingId: 'E0005',
    buildingName: getBN('E0005'),
    location: 'Edificio 005',
    description: 'Reparación junta dilatación (filtraciones a oficinas planta 2)',
    proposedYears: ['2023', '2025'],
    estimatedCost: 48157,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Operatividad (filtraciones)',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-14',
    buildingId: 'E0008',
    buildingName: getBN('E0008'),
    location: 'Edificio 008',
    description: 'Saneado y pintado fachada (proyecto redactado)',
    proposedYears: ['2023', '2025'],
    estimatedCost: 95740,
    priority: 'Conveniente',
    priorityStatus: 'Conveniente',
    risk: 'Estética / Conservación',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-15',
    buildingId: 'E0011',
    buildingName: getBN('E0011'),
    location: 'Edificio 11',
    description: 'Acondicionamiento fachada',
    proposedYears: ['2023', '2025'],
    estimatedCost: 90000,
    priority: 'Conveniente',
    priorityStatus: 'Conveniente',
    risk: 'Estética / Conservación',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-16',
    buildingId: 'E0028',
    buildingName: getBN('E0028'),
    location: 'Edificio 28 (hangar autos)',
    description: 'Acondicionamiento almacén trasero',
    proposedYears: ['2023', '2025'],
    estimatedCost: 46000,
    priority: 'Conveniente',
    priorityStatus: 'Conveniente',
    risk: 'Operatividad',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-17',
    location: 'Cocina cafetería',
    description: 'Reforma integral (revestimientos e instalaciones muy deterioradas, sin salubridad)',
    proposedYears: ['2019', '2021', '2023'],
    estimatedCost: 120000,
    yearOfValuation: '(2023)',
    priority: 'No en 2025',
    priorityStatus: 'No en 2025',
    risk: 'Salud / Operatividad',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-18',
    buildingId: 'E0011',
    buildingName: getBN('E0011'),
    location: 'Edificio 11 (transeúntes)',
    description: 'Sustitución ACS (termos eléctricos -> caldera gasoil + depósito 1500 L)',
    proposedYears: ['2021'],
    priority: 'No en 2025',
    priorityStatus: 'No en 2025',
    risk: 'Operatividad',
    status: 'pendiente',
    unitId: 'ALFEREZ',
    updatedAt: new Date().toISOString()
  },

  // CABO ROIG (Morejón)
  {
    id: 'rti-work-morejon-1',
    location: 'Suelos',
    description: 'Mantenimiento de suelos (desgaste, desniveles, riesgo tropiezos)',
    proposedYears: ['2019', '2021', '2023', '2025'],
    estimatedCost: 48000,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Personas',
    status: 'pendiente',
    unitId: 'MOREJON',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-morejon-2',
    location: 'Aseos',
    description: 'Mantenimiento de aseos (humedades, desprendimientos, corrosión)',
    proposedYears: ['2019', '2021', '2023', '2025'],
    estimatedCost: 30000,
    priority: 'Imprescindible',
    priorityStatus: 'Imprescindible',
    risk: 'Salud / Personas',
    status: 'pendiente',
    unitId: 'MOREJON',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rti-work-morejon-3',
    location: 'Cubiertas',
    description: 'cubiertas (humedades en paredes maestras)',
    proposedYears: ['2019', '2021'],
    priority: 'No en 2025',
    priorityStatus: 'No en 2025',
    risk: 'Estructural',
    status: 'pendiente',
    unitId: 'MOREJON',
    updatedAt: new Date().toISOString()
  },
  
  // OTROS
  {
    id: 'rti-work-otros-1',
    location: 'CMT "Agost"',
    description: 'Revisiones generales sobre el terreno',
    proposedYears: [],
    priority: 'Revisar',
    risk: 'Revisor sobre el terreno',
    status: 'pendiente',
    unitId: 'OTROS',
    updatedAt: new Date().toISOString()
  }
];
